### ISSUE TITLE
Transitions between sources not working properly after upgrade to version 1.4.0

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1009]
Hi, I realise that before version 1.4.0, transitions and crossfades underwent some heavy changes. I can see this in the docs and cookbook. My old definition for transitions in my .liq (which worked in version 1.3.7) stopped working in 1.4.0, which I expected would happen. I don’t need any crossfade effect between sources, which is what the examples in the cookbook all seem to do.
I upgraded to version 1.4.0 from 1.3.7 via opam (on Debian 9) with the following:

`opam install taglib mad lame vorbis cry ssl samplerate magic lastfm inotify liquidsoap`

The transition defintion below no longer fades out the OLD source. It simply cuts the source and begins the NEW source. 

The expected behaviour is:
Fade out OLD source. Skip the track in the NEW source (which was playing before the transition) and then begin the next track from the NEW source. No crossfading between sources is necessary nor wanted.

the transition def is provided below (If this doesn't reproduce the error at your end, I can provide a more detailed script for further investigation)

`def trans(old,new)`
`old = fade.final(duration=10.,old)`
`source.skip(new)`
`new = fade.initial(duration=0.,new)`
`sequence([old,new])`
`end`

**Comment by toots** [comment]
Hi,

Thanks for the informative report. Would you be able to include some logs around the transition? Preferably with `set("log.level",4)`?

**Comment by oranjebloom** [comment]
Hi, 

Sure, here is a log the transition heading in to a 2-minute long program and then heading out of it again. It does everything it is supposed to except fade out the old source. I can provide a log for the exact same thing in 1.3.7 too if needed
[ssr3.log.txt](https://github.com/savonet/liquidsoap/files/3776715/ssr3.log.txt)

**Comment by oranjebloom** [comment]
let me know if you need to look at the .liq script as well. I've tried to keep it as minimal as possible

**Comment by toots** [comment]
Thanks for the logs! I'm surprised as I don't see the expected logs, such as: `"Simple transition: crossed, fade-in, fade-out."` or `Before: ...`/`After: ...`. Would you mind sharing some of the script as well?

**Comment by oranjebloom** [comment]
Sure. Here it is ... this is the minimal version of the script.
[ssr3.liq.txt](https://github.com/savonet/liquidsoap/files/3777250/ssr3.liq.txt)

**Comment by toots** [comment]
Ok, thanks. I'm surprised that it even worked out on `1.3.7`. I have enough to test it locally now, though. Give me a minute to try it myself and I'll get back to you.

**Comment by oranjebloom** [comment]
I believe the I acquired the code from you quite some time ago (about 18 months ago) on the mailing list.

**Comment by toots** [comment]
> I believe the I acquired the code from you quite some time ago (about 18 months ago) on the mailing list.

I believe this transition code was intended for `crossfade` transitions, not `switch`/`fallback` transitions. Typically, `swing` and `fallback` transitions only have part of the current frame (`0.04s` by default) when computing transitions, so a `10.` sec fade out would never work..

**Comment by oranjebloom** [comment]
> I believe this transition code was intended for `crossfade` transitions, not `switch`/`fallback` transitions. Typically, `switch` and `fallback` transitions only have part of the current frame (`0.04s` by default) when computing transitions, so a `10.` sec fade out would never work.

The cookbook examples all seem to try to cross the sources. Are you able to provide an example (or an edit of my old code) where there is no overlap of the sources?

**Comment by oranjebloom** [comment]
So, I've actually taken the first (switch-based) transition example straight from the cookbook for version 1.4.0, and replaced the old transition (which you investigated above). The example I used is below. I just wanted to see if it would work in the .liq script I shared with you in this thread. It still doesn't fade out. Would you mind confirming this at your end by using the script I provided and the transition below?

`def trans(a,b)
def add_transition_length(_) =
[("liq_transition_length","15.")]
end

transition =
add(normalize=false,[ sequence([ blank(duration=5.),
fade.in(duration=10.,b) ]),
fade.out(duration=10.,a) ])
map_first_track(map_metadata(add_transition_length),transition)
end`

**Comment by toots** [comment]
Thanks for this clarification. I now see the part of the doc you are referring to and the changes in transitions between `1.3.7` and `1.4.0`. What surprises me is the duration of that fade out. Did you actually had `10` seconds of fade out on the old source with `1.3.7`?

I can make it work in `1.4.0`, this way:
```ruby
def play_s1() =
  file.exists("/tmp/s1")
end

def play_s2() =
  file.exists("/tmp/s2")
end

def transition(a,b) =
  add(normalize=false,[
    sequence([
      blank(duration=5.),
      fade.in(duration=10.,b)
    ]),
    fade.out(duration=10.,a)
  ])
end

s = switch(
  track_sensitive=false,
  transitions=[transition,transition],transition_length=15.,[
  (play_s1,s1),
  (play_s2,s2),
])
```

*however* this will only fade out the ending track only if the transition happen in the middle of a track, which requires `track_sensitive=false`. Otherwise, there is no data available.

Your script seems to only need to increase the default `transition_length`, `15`. is the transition in the example above or `10.` in the script you have shared.

**Comment by oranjebloom** [comment]
Hi and thanks for continuing to look at this. I realise that you have a lot going on.

In answer to your question …
>What surprises me is the duration of that fade out. Did you actually had 10 seconds of fade out on the old source with 1.3.7?

Yes. I've reverted back to 1.3.7 for now (until I find a solution for this issue) and the transition below provides me with a 10 second fade out. It works really well. It also skips the previously playing track (in new) because you don't want listeners to come into the middle of the track of the (default) fallback program.

`def trans(old,new)` 
`old = fade.final(duration=10.,old)` 
`source.skip(new)`
 `new = fade.initial(duration=0.,new)` 
`sequence([old,new])` 
`end`

I have three questions about the example in your reply.

1. I haven't seen sources defined like that before. I assume that part of the code is NOT mandatory in order to get a successful fade out. Right?

2. Where would you position `source.skip(new)` in that example? My trail and error so far have caused the script to break.

3. Did you use a scheduler in your test? I assume you did in order to get the transition to fade out during the middle of a track (as you mentioned). Your example isn't working in my .liq but I think it's because it doesn't like the way I've set up my scheduler. I've coupled them below. It would help me if you could test the example below - I suspect it won't work for you either ... possibly because of `({true},s1)]))` at the bottom of the scheduler
 
`def transition(a,b) =`
`add(normalize=false,[`
`sequence([`
`blank(duration=10.),`
`fade.in(duration=0.,b)`
`]),`
`fade.out(duration=10.,a)`
`])`
`end`

`radio = mksafe(switch(track_sensitive=false,transitions=[transition,transition],transition_length=10.,[`
`({22h04-22h05},s2),`
`({true},s1)]))`

**Comment by gammaw** [comment]
Hi, 

I have a similar issue. We had the following transition which worked with 1.3.7: 

```
def transition_into_show(j,a,b)
	sequence([fade.final(duration=5.,a),j,b])
end
```

The corresponding switch is something like this: 

```
radio = switch(track_sensitive=false, transitions=[
    transition_into_show(playlist_jingle),
    transition_into_show(playlist_jingle),
    transition_into_off(playlist_jingle_after_show) ], [
    #Live DJ
    ({!live_enabled}, live),
    ({7w and 23h-23h15m}, once(playlist_midnight_song)),
    ({true}, radio) ])

```

Now instead of fading out source `a` there is a hard cut on the source. I couldn't fix it so far. Do you have a recommendation/work-around? 

I attach the corresponding log: 

[ls_log_1.4.0.txt](https://github.com/savonet/liquidsoap/files/3883428/ls_log_1.4.0.txt)

**Comment by gammaw** [comment]
Hi guys, any plans when a 1.4.1 release is planned? Azuracast is using 1.4 and this issue prevents us from updating there. Thanks!

**Comment by toots** [comment]
Hi there!

Unfortunately, I don't think that we're gonna be able to go back to the way the option was working in `1.3.7`. If anything, the next major release will probably see all switch/fallback/etc. transitions removed in favor of using only crossfade.

First, let me explain as best as I can: Liquidsoap operates using a frame, which usually contains about `0.04s` of audio data. Switch/fallback/.. sources decide to switch sources during one frame. That means that, on source switch there is really as much as `0.04s` of audio data available from the ending source.

Now, what was going on up to version `1.3.7` is that, when switching from `old_source` to `new_source` with a transition, we weren't really switching to`new_source` but to the source returned by `transition(old_source, new_source)`.

Now, if you think about the script running for a long time, which it is built for, this would lead to situations where that source will grow such as:
* `transition(old_source, new_source)`
* `transition(transition(old_source, new_source), new_source)`
* `transition(transition(transition(old_source, new_source), new_source), new_source)`

Which would lead to stack overflow issues.

There were some workaround in place to try to avoid this but they weren't working in all cases and were too prone to issues, so in `1.4.0`, transitions were changed to only operator on a pre-buffered amount of audio, which effectively removed the possibility to, for instance, have long fade out on `old_source`. This is also why we might simply remove the feature there since having at most `0.04s` of audio data doesn't really allow for meaningful transitions.

But, don't fret! There will still be a way to provide this functionality and this way is through the `crossfade` operator, which is built from the beginning to handle long crossfades and etc.

I'm currently working with @oranjebloom to implement this using the `crossfade` operator. Essentially, it consists of:
* Adding a special metadata to each source in your switch/fallback/etc..
* Using these metadata in the `crossfade` to trigger the transitions that used to be on the switch level.

Here's a quick sketch of it:
```
def tag(s,tag) =
  def f(_)
    [("source_tag","opensource")]
  end
  map_metadata(insert_missing=true,f,s)
end

s1 = ....
s1 = source_tag(s1, "s1")

s2 = ...
s2 = source_tag(s2, "s2")

s = switch(..., [(..., s1), (..., s2)])

def trans(_,_,old_m,new_m,old,new)
  if list.assoc(default="","source_tag",old_m) != list.assoc(default="","source_tag",new_m) then
    ...old switch transition goes here...
  else
    ...regular transition goes here. If you don't want a transition just use:
    sequence([old,new])
  end
end

# Make sure duration is long enough to support the maximum
# transition duration you need here:
s = cross(duration=10.,trans,s)
```

Hope this makes sense. I'll update y'all when we have this working on @oranjebloom's script!

**Comment by gammaw** [comment]
@toots thanks for the explanation! Sure, if there will be a new way, perfect! Is there a workaround until you fix the script or fading out/fading in between sources won't be working with 1.4.0?

**Comment by toots** [comment]
Hi @gammaw! The solution described above should already work with `1.4.0`, I'm waiting to confirm that we're not running into any issue with it, though. Otherwise, my suggestion would be to stick with `1.3.7` until this is confirmed working `100%`..

**Comment by toots** [comment]
Hey guys.

I had a deeper dig in the code and realized that it should actually work as before, provided that you set the correct `transition_duration`.. 

@gammaw for instance, you should try something like this:
```
def transition_into_show(j,a,b)
  sequence([fade.final(duration=5.,a),j,b])
end

radio = switch(track_sensitive=false, 
  transition_duration=10. # This should be: 5. + max duration of a jingle..
  transitions=[
    transition_into_show(playlist_jingle),
    transition_into_show(playlist_jingle),
    transition_into_off(playlist_jingle_after_show) ], [
    #Live DJ
    ({!live_enabled}, live),
    ({7w and 23h-23h15m}, once(playlist_midnight_song)),
    ({true}, radio) ])
```
I'm also testing with @oranjebloom for the same quick fix..

**Comment by gammaw** [comment]
@toots thanks. Do you mean `transition_length`?  `transition_duration` lead to syntax error and I didn't find it in the API reference either. I tried with `transition_length` and it didn't work (still no fading out).

**Comment by gammaw** [comment]
I also tried a simplified version of your script. I removed the tagging and wanted to test if fading out works. This was my code. The `radio` source is a simple playlist with a couple of songs. As you can see I use a live source for testing because then I can easily trigger a source switch. Unfortunately, I hear no fading out: when the live source connects the `radio` source stops playing abruptly. Am I doing something wrong?   

```
def trans(_,_,old_m,new_m,old,new)
  sequence([fade.final(old),new])
end

radio = switch(track_sensitive=false, [
    #Live DJ
    ({!live_enabled}, live),
    ({true}, radio) ])

# Make sure duration is long enough to support the maximum
# transition duration you need here:
radio = cross(duration=5.,trans,radio)

```

**Comment by gammaw** [comment]
Hi guys, do you have any news on this or hint in what direction we could experiment?

**Comment by toots** [comment]
Hi,

At this point, I suspect a bug in the code & need to take the time to try to reproduce and fix. Meanwhile, I would suggest to stick to `1.3.7` if the exact feature is required or try the `crossfade` trick explained above.

Thanks for y'all patience..

**Comment by gammaw** [comment]
I see. Thanks! I tried with `cross` (not `crossfade`) based on your proposal but it didn't work either (see my post https://github.com/savonet/liquidsoap/issues/1009#issuecomment-559870800). If you have any other hint for a workaround with `crossfade` or other, please let me know, I would be happy to try it.

**Comment by gammaw** [comment]
@toots I hear fading! I replaced `fade.final` for `fade.out` in my last example and the leaving track will be faded out. So happy! :) 

I wanted to go a step further and add jingles in between the old and the new track, like this: 

```
def trans(_,_,old_m,new_m,old,new)
  sequence([fade.out(old),playlist_jingle,new])
end

radio = switch(track_sensitive=false, [
    #Live DJ
    ({!live_enabled}, live),
    ({true}, radio) ])

# transition duration you need here:
radio = cross(duration=5.,trans,radio)
```

I simply added `playlist_jingle` into the sequence. Syntactically it's ok but it kills the `radio` source after the old track has been faded out. No jingle is played, sometimes I hear some white noise kind of thing and the `radio` source won't come back after disconnecting the `live` source.

This is what I see in the log:

`2019/12/05 10:58:45 [dummy:3] Source failed (no more tracks) stopping output...
`

Do you have a hint how we could add those jingles?

**Comment by gammaw** [comment]
@toots even without jingles `fade.in` (`fade.initial`) won't work for me in this context. Like before, I have the following code extended with `fade.in`:

```
def trans(_,_,old_m,new_m,old,new)
  sequence([fade.out(old),fade.in(new)])
end

radio = switch(track_sensitive=false, [
    #Live DJ
    ({!live_enabled}, live),
    ({true}, radio) ])

radio = cross(duration=10.,trans,radio)
```

Live is a live source defined via `input.harbor`. The `radio` source is faded out, live source is playing, `radio` returns (after disconnect) but without fading. 

Any idea what fading in is not working for me?

**Comment by gammaw** [comment]
For completeness, this is the definition of the live source:

```
live = audio_to_stereo(input.harbor("/", id="radio_input_streamer", port=8005, user="shoutcast", auth=dj_auth, icy=true, max=30., buffer=5., icy_metadata_charset="UTF-8", metadata_charset="UTF-8", on_connect=live_connected, on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))
live = fallback(id="radio_live_fallback", track_sensitive=false, [live, blank(duration=2.)])

```

**Comment by toots** [comment]
Hey guys,

Good news, I've got a good handle on this issue. There are many problems but I can see all of them now. I'll work on a solution shortly. This will probably be worth a bugfix release.

**Comment by oranjebloom** [comment]
Hi Romain,

Good to hear you have made some progress. Let me know when you are ready to get me to test something from my end.

Cheers
Damian

**Comment by toots** [comment]
For sure & thanks for y'all patience here. I'm trying to figure out what the right course of action is. We need to make this work again but fixing the issue might prove tricky wrt. to other uses of these operators in crossfade typically so I'm taking a little time to think about the specs that we want from them and how to make sure they work with the minimal change to the existing code.

**Comment by oranjebloom** [comment]
I understand completely. Take your rime. I am comfortable here running 1.3.7, so no rush. I just want to be able to keep up to date with the latest Liquidsoap in future as it develops, so this is fundamental to that.
Chat soon

Damian

**Comment by gammaw** [comment]
@toots glad to hear to you found the root cause to all this! Two questions: 
- Do you have an approximate timeline in mind when you would be able to have a new release out? We're also fine with 1.3.7 at the moment but because we are Azuracast users we cannot update there as they're using 1.4. 
- Will the `cross` or any other operator be able to play "jingles" (a 3rd source) like it was possible with `transitions`? Our use case there is basically this: [fade_out_old_source, play_a_jingle_from_playlist, fade_in_new_source].

**Comment by toots** [comment]
Hey guys!

I just pushed a commit that will hopefully fix the issue.

It looks as if you won't even need to recompile liquidsoap to test. Here are the details:

Add the following at the beginning of your script:
```ruby
def mkfade(~type="lin",~start=0.,~stop=1.,~duration=3.,~on_done={()},s) =
  log = log(label="mkfade")

  # Shape functions must map 0. -> 0. and 1. -> 1.
  pi = acos(-1.)
  def sin_shape(x) =
    (1. + sin((x-0.5)*pi))/2.
  end

  curve = 2.
  m = exp(curve-1.) - exp(-1.)
  def exp_shape(x) =
    (exp((curve*x)-1.) - exp(-1.))/m
  end

  curve = 10.
  m = log_e(1.+curve)
  def log_shape(x) =
    log_e(1.+10.*x)/m
  end

  def lin_shape(x) =
    x
  end

  shape =
    if type == "sin" then
      sin_shape
    elsif type == "exp" then
      exp_shape
    elsif type == "log" then
      log_shape
    elsif type == "lin" then
      lin_shape
    else
      log("Invalid type #{type}, using \"lin\"")
      lin_shape
    end

  start_time = ref (-1.)
  def fade() =
    if !start_time < 0. then
      start_time := source.time(s)
    end

    t = source.time(s) - !start_time
    if t >= duration then
      on_done ()
      stop
    else
      if start <= stop then
        start + shape(t/duration)*(stop-start)
      else
        stop + shape(1.-t/duration)*(start-stop)
      end
    end
  end

  fade
end

def fade.final(~id="fade.final",~duration=3.,~type="lin",s) =
  fn = mkfade(start=1.,stop=0.,type=type,duration=duration,s)
  should_play = ref true

  def fn() =
    v = fn()
    if v == 0. then
      should_play := false
    end
    v
  end

  s = amplify(id=id,fn,s)
  switch(track_sensitive=false,[({!should_play},s)])
end

def fade.initial(~id="fade.initial",~duration=3.,~type="lin",s) =
  fn = mkfade(start=0.,stop=1.,type=type,duration=duration,s)
  amplify(id=id,fn,s)
end
```

This should tell liquidsoap to use the fixed versions of `fade.final` and `fade.initial`. Then you can test your transition.

Here's the one that I have used for tests:
```ruby
s = playlist("/tmp/foo")
r = playlist("/tmp/bla")

def f(path) =
  fun () -> file.exists(path)
end

def transition(old, new) =
  sequence(merge=true,[
    fade.final(duration=10.,old),
    fade.initial(duration=10.,new)
  ])
end

s = switch(
  track_sensitive=false,
  transitions=[transition,transition],
  transition_length=20.,
  [
    (f("/tmp/1"), s),
    (f("/tmp/2"), r)
  ])
```

It's pretty convenient, you can control the `switch` by creating and deleting the files `/tmp/1` and `/tmp/2`.

Lastly, don't forget to add `merge=true` when using `sequence` for transitions. Otherwise, a track mark between the two sources will trigger a reselect from the `switch`, which is probably not the behavior that you would expect.

Let me know if that works for y'all!

**Comment by gammaw** [comment]
@toots xmas time! My first tests are working! I'll try it with a more complex example but it's very very promising. Thanks :) 

I was wondering about your https://github.com/savonet/liquidsoap/issues/1009#issuecomment-559598553. Since the script you posted above is not with `cross/crossfade` but with the old `switch` & `transition` wouldn't it potentially lead to the undesired stack overflow issue? Or can it lead to that like with 1.3.7 and is this meant to be a temporary fix?

**Comment by SlvrEagle23** [comment]
@toots Hello! We've been following this issue, and I just wanted to confirm that you committed that same updated fade code directly into the Liquidsoap codebase. If so, we'll look forward to the next tagged release version and update directly to that so that everyone can take advantage of the updated fading logic.

**Comment by toots** [comment]
Ok y'all, `1.4.1` is published, I'm closing this. Thanks for the patience and feedback!!
