### ISSUE TITLE
A common interface for metadata

### ISSUE THREAD

**Issue by CyberDomovoy** [savonet/liquidsoap#1061]
**Is your feature request related to a problem? Please describe.**
Metadata are used everywhere in LS and its dependencies. But there is no common way to handle those (the same type defined several times, a bunch of methods scattered everywhere in code). This doesn't help bettering the code (if we want to improve one part of code, we need to stay aware of how other parts might use what we give them).

**Describe the solution you'd like**
I propose the creation of a new opam library for managing metadata. Thing is, LS is not limited to _audio_ metadata, so we can't simply use a library that handles those and hope it will meet _all_ our needs.

**Describe alternatives you've considered**
In the end, LS is a broadcasting tool, so let's take a look at what is done on this side:
I found this page (https://damdirectory.libguides.com/metadatastandards/audiovisual) which seems to be the best overview of actual metadata standards i could find.
From this list i was particularly interested by:
* MPEG-21: MPEG 7 could be more than enough, but it is still tied to the content type, MPEG-21 metadata are not tied to the format of what they describe. Seems to me the most well-thought and complete way to describe a media broadcast.
    * https://www.researchgate.net/publication/220917936_MPEG-21_in_Broadcasting_Role_in_the_Digital_Transition_of_Broadcasting
    * http://leonardo.chiariglione.org/13-5-mpeg-21/
* EBUCore: Distinguish content and format metadata. https://tech.ebu.ch/MetadataEbuCore
* PBCore: Seems quite easy to understand and implement, but i'm not so sure about its modularity. http://pbcore.org/what-is-pbcore
* SMPTE frameworks: Well... This one is not really about metadata itself; but it is quite impressive about how to handle a broadcast from multiple sources and to multiple outputs. When i see this, i can't help but think that it is what LS is about, apart from the fact that all this mix and match is done in the software instead of other a IP network (which in the end is not that different). I truly believe we could get a lot of inspiration from this beast.
    * https://netinsight.net/resource-center/blogs/what-is-smpte-2110-and-nmos-all-about/
    * https://www.smpte.org/smpte-st-2110-faq

But yeah, i propose a lot, and i should finish what i started on requests first :D
Still, i'd like to keep these ideas not too far so that we can come back to it in time.

**Comment by toots** [comment]
Please don't stop bringing up topics like that!

As I see it, metadata in liquidsoap really only originally referred to metadata as in track/file metadata, that is information that describe author/title/album/.., so something like id3 specifications and etc.

In past and in order to not have to re-invent the wheel on those, we have used [taglib](https://taglib.org/), which can normalize multiple different formats. On certain cases, however, we have to resort to format-specific readers such as when reading fields that only exist in certain format or aren't supported in a uniform way with taglib. @smimram's work on track cover is an example.

The other case of metadata are those for internal use, overriding values, passing source ID etc. These metadata are merged with the track-specific ones in a way that can, indeed, be confusing.

In the code, there are two main types:
* `Meta_format.export_metadata`: an internal opaque type. Metadata of this type can contain any value, track info, internal stuff, etc.
* `Frame.metadata`: a `(string,string) Hashtbl.t`. Metadata of this type are public and filtered according to the `encoder.encoder.export` setting (defaults to: `["artist","title","album","genre","date","tracknumber","comment","track","year","dj","next"]`)

The two different types are on purpose, to force the programmer to have to filter the metadata before passing them to an output..

I think the other metadata you are referring to are more broadcast-specific metadata. I don't think that we are set to deal with those at the moment.

**Comment by CyberDomovoy** [comment]
>     * `Frame.metadata`: a `(string,string) Hashtbl.t`. Metadata of this type are public and filtered according to the `encoder.encoder.export` setting (defaults to: `["artist","title","album","genre","date","tracknumber","comment","track","year","dj","next"]`)
> 
> 
> The two different types are on purpose, to force the programmer to have to filter the metadata before passing them to an output..

I remember some time ago submitting a patch to ocaml-ogg or something to remove metadata filtering at the encoder level, because i wanted some specific data sent to my player (show name, episode number, episode title...). IMHO, filtering should be done the other way: have a blacklist of keys to _not_ send. ID3 and metadata in general, is quite a free format, and who knows what information someone might choose to convey using those, it would be a pity to loose those just because they are not part of the "chosen ones". On the other end, there are some i know i will _never_ want sent: data regarding my privacy (maybe that decoder i use adds some tags about where and when i did it?)
But anyway, that's another subject.

> I think the other metadata you are referring to are more broadcast-specific metadata. I don't think that we are set to deal with those at the moment.

Well, i don't really have an idea about anything specific, i was thinking about metadata in general, and actually more about _data_ than metadata: it can be close captions, news, audio description, info about scheduled events, ads.... anything we can see in today media experience, and anything we haven't thought of yet.

I would also highly recommend taking a look at NMOS (https://amwa-tv.github.io/nmos/), which is a set of specs complementing (maybe even superseding) SMPTE ST 2110. Bonus: all their work is available on github, and the doc is great (unlike SMPTE, which won't even give you the specs without paying). Their concept of having a REST API on and for almost everything is quite interesting, and once again, i believe LS could benefit a lot from this work. To get an idea of why, i recommend starting with https://amwa-tv.github.io/nmos/branches/master/NMOS_Technical_Overview.html#nmos-model-and-terminology and https://amwa-tv.github.io/nmos-id-timing-model/.
While reading all these, please keep in mind that:
* REST API doesn't imply HTTP, an ocaml module can very well define one
* Transmitting a flow doesn't necessarily imply some network communication, it can be a module function, a buffer, a file ...
* Same thing for anything in these specs implying some sort of network protocol: it can be translated to a "in code" transmission. The benefit of handling it _as_ a network protocol is obvious: if you ever need to "split" your process so that some part of it is done externally (a machine dedicated to decoding for example), than it is easily done: instead of an internal transmission, it will be a network one, the code/API stays the same, only the way data is transmitted changes.
* Even if NMOS is quite complete and could be seen as a complete stack on its own, keep SMPTE in mind, it _really_ is a base to use NMOS on, some concepts there are very great (IP level transmission, dump blanking info on videos...) and allow for less bandwidth, faster transmission...
