### ISSUE TITLE
Video streaming

### ISSUE THREAD

**Issue by drno88** [savonet/liquidsoap#1079]
Good day. Firstly - thank you for the product, it is very good!
The question is - how can I use Liquidsoap scheduler to play video WITHOUT transcoding? What format should it be in? What do I need to register in output. ......     to achieve the minimum load?

OS - Ubuntu
liquidsoap and the video will play on localhost

Perhaps I can pass output for example in VLC/ or other videoplayer?

the line I'm using now and it works, but transcoding ...  icecast not required
```
output.external(%avi,"ffmpeg -re -f avi -i pipe:0 -f webm -content_type video/webm -c:v libvpx -b:v 2000K -flags:v +global_header -
cpu-used 0 -deadline realtime -quality realtime -auto-alt-ref 0 -c:a libvorbis -flags:a +global_header icecast://s
ource:passwerd@www.blahblahblah.com:8000/test.webm",mksafe(input))
```
then I connect vlc to the link icecast.

thanks for the answer!

**Comment by smimram** [comment]
Unfortunately, the current architecture of Liquidsoap makes it very hard to support passing audio/video without transcoding (we need to be able to perform transitions, etc.). In one word: don't expect it to be doable easily with Liquidsoap in a near future, sorry :(

**Comment by drno88** [comment]
Thanks for your reply. Yes, I understand about transitions, and more.

In that case, which option in terms of "speed" and "CPU resources" should I use?

ffmpeg + mp4 h264  (ffmpeg zerolatency)
or flv
Maybe - HLS?

**Comment by autonarcosis** [comment]
There a large amount of factors involved.  The frame size, the frame rate, what CPU being used, what extensions the CPU supports.  Encoding video is resource intensive.  Since this is live encoding your goal with ffmpeg is to achieve 1x or real time encoding.  The system shouldn't be tasked with other processes that cause the delay in the encoding process.

In my experience using limited mid-range consumer CPUs the libvpx and libx264 encoders in ffmpeg are the best.  Ffmpeg also supports GPU accelerated encoding for H264.  The libvpx enocder is good for standard definition video and is supported platform wide.  The libx264 encoder is good up to 1080p (again CPU dependent to be able to encode it in real time).  H264 is also now also supported on most all platforms.

I don't recommend FLV. Flash needs to just die.

DASH and HLS are more containers/platforms which you can use various encoders within them.  Using either you will need some sort of enterprise storage device (HDD/SSD) that is meant for high amount of data writing or you will find yourself replacing them often.  DASH/HLS eats hard drives for breakfast.  Depending on who/what is receiving the stream I recommend DASH.  Icecast is quickly becoming irrelevant and way behind when it comes to video streams.  Its hard pressed to get people to install VLC in order to get them to watch your stream.  Remember there are adults in their mid to late 20's now that have never touched or know what an mp3 file is.

Hope this gives some insight.

**Comment by drno88** [comment]
autonarcosis, Thanks for your reply. but my task is in local playback, in fact I am making a video that will simply play in the background on tv screens, using a nettop, by hdmi.
I am not going to display content on the Internet. maximum to the local network ... if there are several TV screens to synchronize them.It's just that the Liquidsoap scheduler is very convenient for me, because has great flexibility

I managed to achieve the desired as follows. I brought the stream directly to VLC. after starting X-sessions, I have a script running, here is part of the config.

output.external(%avi,"cvlc - -I dummy", music)  key "-"  on VLC = "pipe" on ffmpeg

So I got a video stream that is controlled directly by the liquidsoap in the VLC

But I don’t get the sound in this way. what ando to me to choose a parameter instead "%avi" ???

Broadcasting with a minimum load, on rtsp - a piece of the config, however in transcoding 
output.external(%avi,"cvlc - --sout='#transcode{venc=x264{preset=ultrafast},vcodec=h264,width=1280,height=720}:duplicate{dst=rtp{access=tcp,sdp=rtsp://:8002/1}}'", music)

(((when trying to run just duplicate - error -  cannot add this stream (unsupported codec: I420)
this config 
output.external(%avi,"cvlc - --sout='#duplicate{dst=rtp{access=tcp,sdp=rtsp://:8002/1}}'", music)

Can you tell me which codec I need to encode the video to avoid this error?

**Comment by autonarcosis** [comment]
Here is a basic 720p libx264 and aac RTSP stream using ffmpeg;

`output.external(%avi,"ffmpeg -re -i pipe:0 -f rtsp -muxdelay 0.1 -c:v libx264 -profile:v main -level:v 4.0 -pix_fmt yuv420p -b:v 3000k -c:a aac -b:a 64k -rtsp_transport tcp rtsp://server/live.sdp", videoplaylist)`

It will take me a couple days to figure out a VLC solution.  The unsupported codec error is most likely due to a pixel format error.  The %AVI output of Liquidsoap contains 4:4:4 chroma and libx264 supports 4:2:0 chroma in it's baseline and main profiles. Hence the pixel format setting in the ffmpeg example above.

**Comment by autonarcosis** [comment]
I currently do not have X on my servers to test that type of output.  However, I am getting the same no audio output with the RTSP stream I've come up with.  The %AVI does output both video and audio.  The audio is pcm_s16le and VLC seems to have issues with it.  I haven't figured out a solution for the RTSP stream.

`output.external(%avi,"cvlc -I dummy --vout vdummy --aout adummy fd://0 --verbose=3 --sout='#transcode{vcodec=x264,vb=800,acodec=mp4a}:rtp{name=dst=0.0.0.0,port=5080,sdp=rtsp://server.name.here.com:1935/live.sdp}'", videoplaylist)
`
fd://0 is input pipe for VLC. Makes it easier to read than -. 

Add --verbose=3 to your basic cvlc - command and see if there are audio errors. As I believe you are on the right direction by sending the video stream out via HDMI to the screens.

**Comment by autonarcosis** [comment]
I got no where with VLC. However, ffmpeg can output to the screen.  Since you have X11 something like this might work;

`ffmpeg -re -i pipe:0 -map 0:v -f opengl 'test' -map 0:a -f alsa default
`

**Comment by drno88** [comment]
ffmpeg I was not able to get to work yet.
anyway, I would like vlc))

VLC displays video well in fd: // 0, but there is no sound ((
Apparently you need to use another variable, instead of %avi?
When you select the variable %mp3, the sound appears, everything is fine

And as for rtsp - with "transcode" everything works fine and the sound also, I just wanted to do without it, pre-encode the video in the desired format.

That is, we get that the sound output fd: // 0 only works with "transcode"

**Comment by autonarcosis** [comment]
fd://0 is File Descriptor 0 or stdin.

You're "working" VLC command shouldn't be working.  The duplicate does nothing because it's an input not output, the transcode doesn't do anything as there is no output. It's an invalid chain.

It fails in Liquidsoap because VLC has nothing to play because there is no input set.

Use --verbose=3 with cvlc and vlc.  It will tell what it is doing and why something fails.

Did you try the ffmpeg example to opengl display and alsa I posted?  ffmpeg also supports sdl, sdl2, frame buffer hardware video output and alsa, pulse, jack for hardware audio output.

For ffmpeg -loglevel verbose or -loglevel debug will show you what ffmpeg is doing and why something fails.

**Comment by smimram** [comment]
We now have support for playing videos without transcoding, see [there](https://www.liquidsoap.info/doc-dev/encoding_formats.html) and [the book](https://www.liquidsoap.info/doc-dev/book.html).
