### ISSUE TITLE
add mime type audio/opus

### ISSUE THREAD

**Issue by pedro-nonfree** [savonet/liquidsoap#1089]
**Describe the bug**

Add mime type for audio/opus

**To Reproduce**

sender

```
set("log.file.path", "/tmp/script.liq.log")

# src https://www.liquidsoap.info/doc-1.3.3/reference.html#output.udp

# send mixer output -> thanks https://sourceforge.net/p/savonet/mailman/message/28168771/
#   pacmd list-sources | grep "name:"
# (get the one with .monitor at the end)
mysoundcard="alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
source=input.pulseaudio(device=mysoundcard)

output.udp(%opus, host="192.168.16.80", port=5004, source)
```

receiver

```
set("log.file.path", "/tmp/script.liq.log")
out(input.udp(host="192.168.1.2", port=5004, buffer=0.05, "audio/opus"))
```
**Expected behavior**

To receive udp in opus, but what happens is:

```
Error 7: Invalid value:
Cannot get a stream decoder for this MIME
```

works great with mp3 (`%mp3` in sender and mime type `audio/mpeg` in receiver), I am just wanting to get even lower latency because of a greater protocol for that

as you see, I'm reducing the buffer, how much I can do it? with 0.05 mp3 starts to have more glitches :), let's see where I can arrive with opus

**Version details** and **Install method**
 - OS: Debian 10 (on sender `apt install liquidsoap` (1.3.3) on receiver installed with opam (1.4.1)

**Comment by autonarcosis** [comment]
It's an erroneous or vague error that the client doesn't know what the incoming data is.  Mime types are not negotiated.

In order to get this to work with Opus codec (encapsulated in OGG container) you have to start the receiver first, then the sender.  In this situation, Liquidsoap may not work as it requires a working source.  Might want to look into using the harbor input/output methods.

Also, from what I can remember, I believe the UDP buffers for Linux kernels are set relatively low by default. Be sure to check if they are at acceptable settings for what you are doing/expecting.

**Comment by toots** [comment]
Fixed in c2b2ab71!

**Comment by pedro-nonfree** [comment]
thanks @toots !!!!

I would like to test this but I don't know how to do it

https://www.liquidsoap.info/doc-dev/install.html

I did

```
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add liquidsoap .
```

and

    opam install liquidsoap

or

    opam upgrade liquidsoap

with no effects :(

`liquidsoap --version` is still 1.4.1

**Comment by toots** [comment]
Weird. Any details on your OS?
