### ISSUE TITLE
ERROR while compiling liquidsoap.1.3.7

### ISSUE THREAD

**Issue by diaverso** [savonet/liquidsoap#1158]
**Describe the bug**
I am installing Centova Cast.When installing it I use the installation guide on this page
https://centova.com/doc/cast/installation_manual/02_quick_installation
I use the commands that put it and I use the command "./install.sh `--icecast-all"` to install the script.
The script works correctly, but when it gets to the liquidsoap section, it gives an error when compiling
Error:
https://gist.github.com/diaverso/f74634e7818c0f3f64decb9123d7534e

**To Reproduce**
wget -O install.sh install.centova.com/LICENSEKEY
chmod a+x ./install.sh
./install.sh --icecast-all

**Expected behavior**
Will compile and install correctly

**Version details**
 - OS: Centos 7
 - Version: 1.3.7

**Install method**
Installed via opam

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/download.html)

**Comment by ahmedbodi** [comment]
Encountering the same issue with a vm thats been built repeatedly for the past number of months

**Comment by smimram** [comment]
Re-pasting my answer here instead of the gist:

Quick fix:
```
opam install fdkaac.0.3.1
```
before installing.

It seems that version 0.3.2 is not compatible with Liquidsoap 1.3.7...

and the answer:

I found I needed to use `ffmpeg.0.2.1` and `fdkaac.0.2.1` for a recent 1.3.7 install via Opam on Debian Stretch

fdkaac >0.2.1 was failing for some reason.

@toots we should add conflicts in opam files...

**Comment by toots** [comment]
There's a PR pending for this: https://github.com/ocaml/opam-repository/pull/16188 I'll close this one now, keep an 👁️ on the other one!
