### ISSUE TITLE
gtts: incompatible number of channels

### ISSUE THREAD

**Issue by codeofdusk** [savonet/liquidsoap#1179]
In my script:
```none
set("server.telnet", true)
set("server.telnet.port", 1234)
...
# A special queue for smooth_add requests
special = request.queue(id="special")
...
radio = smooth_add(delay=0.5, p=0.15, normal=radio, special=special)
...
radio = audio_to_stereo(radio)
...
output.icecast(%mp3.vbr,
...,
radio)
```

Then, on the telnet server, I try:
`special.push gtts:testing testing`

In the logs, I get:
```none
2020/04/27 23:50:47 [decoder.ffmpeg:3] File "/tmp/liq-process1f578d.mp3" has an incompatible number of channels.
2020/04/27 23:50:47 [decoder.mad:3] File "/tmp/liq-process1f578d.mp3" has an incompatible number of channels.
2020/04/27 23:50:47 [decoder:3] Unable to decode "/tmp/liq-process1f578d.mp3" as {audio=2;video=0;midi=0}!
```
And no TTS output on the stream. What's going wrong?

**Comment by smimram** [comment]
The problem is that the tts output is mono and we need stereo here. I had started some work in #1036 to fix this. Maybe it's time to get back to that.

**Comment by smimram** [comment]
Actually, I suspect that a recent change in the way we handle channels might have broken things. Namely, the following is working
```
s = audio_to_stereo((single("gtts:Hello, world!"):source(1,0,0)))
out(s)
```
but not
```
s = audio_to_stereo(single("gtts:Hello, world!"))
out(s)
```
(it says that it cannot decode the result of gtts as stereo...)

@toots any idea on this?

**Comment by toots** [comment]
Yes. That's the same issue that @mbugeia was reporting earlier today. The type for `audio_to_stereo` is :`source(audio='a, ...) -> source(audio=2, ...)`.

That means that, at runtime, the input source, unless specified, is expected to be sending the default global audio channels, which is 2. When the source is in fact sending mono, the crash happens.

This was silently ignored in previous code because the frame content was reorganized implicitely, which was removed during https://github.com/savonet/liquidsoap/pull/1083.

The proper fix is to update all decoders to be able to implicitly convert audio channels, which would also make `audio_to_stereo` unnecessary in many cases and fix regular issues with `input.harbor`, `playlist`, etc. silently dropping files or DJs that are sending mono instead of stereo and vice-versa.

However, I would like to take the time to do it properly, in particular leveraging, when present, on ffmpeg's channel layout conversion for converting e.g. 5.1 into stereo, which is not a trivial task and cleaning up the decoder's code that is currently slightly messy.

Meanwhile, it should be possible to fix the issue by forcing the type of the source inside the `audio_to_stereo` to the expected type, just as @smimram explained above.
