### ISSUE TITLE
cURL error when playing remote Icecast MP3 stream from URL

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#1199]
We've received a number of comments on AzuraCast that remote URL playlists simply haven't worked for quite some time now, and while we assumed that this had already been submitted as an issue here on the Liquidsoap repository, it doesn't appear that the specific issue actually _has_ been recorded here.

The log below includes our full annotated response from our AutoDJ; this is supplied via a `request.dynamic.list` response and is annotated with a specific length because the "Remote URL" playlist is scheduled, so we only want it to play for a specific period of time.

```
2020/05/09 06:02:18 [lang:3] AzuraCast Raw Response: annotate:length="3600":https://demo.azuracast.com/radio/8000/radio.mp3
2020/05/09 06:02:18 [procol.external:3] Failed to fetch mime-type for https://demo.azuracast.com/radio/8000/radio.mp3.
2020/05/09 06:02:18 [procol.external:3] No known file extension for mime: 
2020/05/09 06:02:38 [lang:3] Failed to execute curl -sL "https://demo.azuracast.com/radio/8000/radio.mp3" -o "/tmp/liq-process35f874.osb": ("timeout", "19.4904370308")
```

This occurs regardless of whether the `set("decoder.mime_types.mad", ["audio/mpeg", "audio/mpeg3", "audio/mp3"])` setting is explicitly specified or not (this was suggested as a solution to a related issue).

Oddly enough, executing the cURL command specified via a terminal inside the same Docker container used by Liquidsoap actually _works_ without any issue, so it's unclear why Liquidsoap attempting to execute this command fails. Also worth noting that there are no changes made in our configuration to the default sandboxing settings, so there shouldn't be anything there limiting it from working.

**Comment by toots** [comment]
Hi,

Due to the nature of `url`, which can contain complex queries such as `http://host/path/to/resource?arg=foo&bla=gni`, when downloading a media file, we rely on their [mime type](https://en.wikipedia.org/wiki/Media_type) to infer a file extension. This code covers it (from `protocols.liq`):
```ruby
  extname =
    if list.mem(mime, ["audio/mpeg", "audio/mp3"]) then
      "mp3"
    elsif list.mem(mime,["application/ogg", "application/x-ogg",
                         "audio/x-ogg", "audio/ogg", "video/ogg"]) then
      "ogg"
    elsif list.mem(mime, ["audio/flac", "audio/x-flac"]) then
      "flac"
    elsif list.mem(mime,["audio/mp4", "application/mp4"]) then
      "mp4"
    elsif list.mem(mime,["audio/vnd.wave", "audio/wav",
                         "audio/wave", "audio/x-wav"]) then
      "wav"
    else
      log(level=3,"No known file extension for mime: #{mime}")
      "osb"
    end
```

It is pretty reasonable to expect `http` servers to set the proper `Content-Type` header when serving local files. It would seem that, in your case, the `http` server does not set that header.

However, a missing `mime` type should not fail the whole process. As you can see above, with no `mime` type, we just use the dummy `.osb` file extension.

What it looks like, I believe, is that your trying to download a live stream from a icecast server. In this case, this will fail because the stream does not end so the process times out.

If you want to download only a potion of the stream, you would need to implement your own protocol to cover this use case. Alternatively, you can use `input.http` for pulling a live stream.

I'll close this issue here, feel free to follow-up on our slack or here if you think there still is an issue with `liquidsoap`.

**Comment by SlvrEagle23** [comment]
@toots So there's no way, other than `input.http` to play an ongoing remote stream? I can't annotate that via the dynamic queue in any way?

**Comment by toots** [comment]
Well, a `HTTP` `GET` request on a remote icecast stream never terminates, I believe a `curl` call on it has to be manually terminated. Thus, you'd need to figure out a way to properly do that in liquidsoap as well.
