### ISSUE TITLE
Different number of transitions and sources in "switch" function (in newer Liquidsoap versions?)

### ISSUE THREAD

**Issue by gammaw** [savonet/liquidsoap#1205]
I'm testing v1.4.2 and I noticed a difference compared to earlier versions. I remember that the following source would be invalid because the number of transitions (2) differs from the number of sources (3). As a result, Liquidsoap would throw an error. 

In the current version Liquidsoap seems to accept any number of transitions. I can imagine that it's a feature (not a bug) because it makes the language robuster, but it takes away a valuable validation in our case: we have over 50 sources in a switch, in a configuration that is frequently edited. It's easy to forget to add or remove transitions. Also, I'm not sure about the meaning of below definition: which transition would belong to which source? 

```
source_invalid = switch(track_sensitive=false, transitions=[
    transition_into_show(playlist_jingle),
    transition_into_off(playlist_jingle_after_show) ], 
    transition_length=60., #max duration of jingle (60s)
    [
    #Live DJ
    ({!live_enabled}, live),
    #Monday
    ({1w and 5h-5h59m}, once(playlist_show1)),
    ...
    ({true}, radio) ])
```

**Comment by toots** [comment]
Hi! That's a good catch. I'm not sure what has changed or it was intentional. It doesn't look like this logic was touched at least between `1.4.1` and `1.4.2`. Transitions are by default padded with dummy ones so I believe that this was always meant to be pretty tolerant to missing ones or extra ones. 

As for the semantics, the transition at position `n` in the list is executed when the operator switches to the source at position `n` in the list of sources.

Hope this clarifies things. I'm gonna close this issue now. Feel free to come discuss further on slack or re-open if you think that needs to be fixed.

**Comment by gammaw** [comment]
@toots fyi: I found out that it's only syntax error if too many transitions are used in the transitions array (more transitions that sources). And it's like this in 1.4.2 too. Sorry for the confusion.
