### ISSUE TITLE
Investigate metadata caching

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#1307]
See: f40e7b79ef435833a6b64295b3b244ea64f2ef88

Settings tentative `2.0.0` milestone here.

**Comment by martinkirch** [comment]
Hello,
I've regularly observed duplicates in the metadata log: sometimes a track's metadata gets reposted, exactly as it was (including `on_air`), a few tracks later. I think this issue is related to #1476, #1096 and #1541 .

It looks like a Heisenbug occuring only in untrivial scripts... and it still happens after building Liquidsoap 2.0.0+git@7358570d , with [this script](https://gist.github.com/martinkirch/f1a0ac36828ebfbee249061973afd9a7) which boils down to:
```ocaml
# two request.dynamic.list generators
shortmusic = beets("shortmusic", "length:..120")
recentshortmusic = beets("recentshortmusic", "length:..120 added:-2m..")
music = random(id="music", replay_metadata=false, [shortmusic, recentshortmusic], weights=[30, 70])

# usually there's harbor, playlists and crossfades here
complete_program = fallback([music, blank()], track_sensitive=false, replay_metadata=false, id="complete_program")

jingles = delay(300., id="jingles",
    playlist("/home/martin/radio/jingles", mode="random", reload_mode="watch")
)
program_with_jingles = fallback(id="program_with_jingles", [jingles, complete_program], replay_metadata=false)
```
what happens:
* stream starts on a jingle
* `recentshortmusic` starts playing (it has a greater weight)
* `shortmusic` gets selected, plays track AAA, `on_air=t1`
* `recentshortmusic` got selected for two more tracks
* 300s passed so a jingle is inserted
* so far the received log is OK
* `shortmusic` gets selected again, plays track BBB : this time, LS re-POSTs AAA's metadata (with `on_air=t1`). Worse: BBB does not appear in my log (although `shortmusic` played again later).

I still have the log and recording of that test, and can change the script to re-experiment. So far I tried 2 variants:

1. removing the track-insentive fallback - still got a duplicate
2. adding empty transitions (to `program_with_jingles`), as suggested in [this workaround](https://github.com/savonet/liquidsoap/issues/1476#issuecomment-765901080) - no more duplicates

Hope this helps !

**Comment by toots** [comment]
Thank you so much for this report @martinkirch I'll get to it soon.
