### ISSUE TITLE
apt repo for debian stretch returns 403 error

### ISSUE THREAD

**Issue by fukawi2** [savonet/liquidsoap#1332]
**Describe the bug**
Trying to setup the `deb.liquidsoap.info` repository on Debian 'stretch'. The URL returns 403 Forbidden error:

```
# apt update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://ftp.au.debian.org/debian stretch InRelease                                                 
Hit:3 http://ftp.au.debian.org/debian stretch-updates InRelease                                         
Hit:5 http://ftp.au.debian.org/debian stretch Release
Ign:4 https://deb.liquidsoap.info/debian stretch InRelease
Err:7 https://deb.liquidsoap.info/debian stretch Release
  403  Forbidden
Hit:8 http://deb.debian.org/debian unstable InRelease
Reading package lists... Done
E: The repository 'http://deb.liquidsoap.info/debian stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**To Reproduce**
On a Debian 9/Stretch system:

```
echo deb http://deb.liquidsoap.info/debian stretch main >> /etc/apt/sources.list.d/liquidsoap.list
apt update
```

**Expected behavior**
Web server returns repository files.

**Comment by toots** [comment]
Hi! Unfortunately, we are not providing debian repositories. The existing one are still available as of now but `debian stretch` was retired because the distribution is too outdated to build liquidsoap at this point.

We will probably keep the other repository active for a while but they won't be updated. We are not providing debian packages as assets attached to the CI runs at: https://github.com/savonet/liquidsoap/actions

**Comment by fukawi2** [comment]
OK, the docs need to be updated then: https://www.liquidsoap.info/doc-dev/install.html#debianubuntu
