### ISSUE TITLE
Error when using `%theora` without compiled support is cryptic at best.

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#1447]

**Comment by RobinvdGriend** [comment]
I think I'm running into this right now. I've tried both the 1.4.4 product Docker image and a 1.4.4 install through opam. With the Docker image, theora is simplty not provided, but it's not clear how to install the package into the container so that I can use the format.

In the local opam install however, when using the %theora encoding, I get an error message:
```
Error 7: Invalid value:
Couldn't find a decoder for this format
```
I've installed theora using `opam install theora` and have checked whether all system packages a satisfied (they are). I'm using archlinux btw. Is there any way with which I can still use the %theora format?
