### ISSUE TITLE
Complex Boolean predicates in switch operator

### ISSUE THREAD

**Issue by gammaw** [savonet/liquidsoap#1452]
I'd like to have something like this in a `switch`:

`({3w and (5h-5h29m or 6h-6h29m or 7h-7h29m or 8h-8h29m or 9h-9h29m)}, once(playlist_bla))`

Syntactically it seems fine as the LS server could load the configuration. The playlist was scheduled only once at 5am but not at 6am etc. Are such expressions not supported or do they have a different semantic from what I'd expect?

**Comment by toots** [comment]
Hi! I think the problem comes from the `once` operator. It really plays the source only `once` so, when the predicate becomes true again at `6am`, the source wasn't available.

Are you trying to play the playlist one time through and then stop? If so, you might want to have a look at `playlist.reloadable`:

> Read a playlist or a directory, play all files and stop. It returns a pair
> `(reload,source)` where `reload` is a function of type `(?uri:string)->unit`
> that can be used to reload the source and `source` is the actual source. The
> reload function can optionally be called with a new playlist URI, otherwise,
> it reloads the previous URI.

Using this operator, you should be able to e.g. implement transitions which, when switching away from the playlist branch in your switch, calls the reload function so that the playlist is available again the next time around.

Please note that I have on my TODO a complete rewrite of queue operator for liquidsoap 2 and plan on tackling it over the weekend. Hopefully, this should enhance and make these kind of operation more user-friendly.

I'm closing this ticket, feel free to follow-up here or on slack. Thanks!

**Comment by gammaw** [comment]
Thank you! I'll check reloadable. Can you tell me when `once` will be available again? We're using it successfully to play tracks that recur weekly. In other words, is there a predefined "validity" for `once`?
