### ISSUE TITLE
Inotify file.watch does not work

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1549]
The implementation of `file.watch` with inotify does not seem to work anymore. In the following script, the function `update` never gets called:
```
def update()
  v = file.contents("volume")
  print("New volume is #{v}.")
end
ignore(file.watch("volume", update))
output.dummy(blank())
```
If I disable inotify in `Makefile.defs`, we default to the "dummy" implementation of `file.watch` which performs as expected.

**Comment by toots** [comment]
I can't reproduce. Could you detail the steps that you are taking?

**Comment by smimram** [comment]
It seems that a more basic example is working indeed:
```
fname = "/tmp/file"
process.run("touch #{fname}")
file.watch(fname, {print("File was modified!")})
output.dummy(blank())
thread.run(every=2., {file.write(data="#{time()}", fname)})
```

**Comment by smimram** [comment]
Even the other example is working. I don't know what happend...

**Comment by smimram** [comment]
Ok, so you can reproduce with #1586. Note that when `file.watch` is run in a thread (cf the test `tests/language/file.watch.liq`) there is no problem, which seems to indicate an issue with the scheduler (possibily related to the explanation of #1577)?

**Comment by toots** [comment]
Would the explanation for #1577 be satisfactory here as well?

**Comment by smimram** [comment]
I think the message of #1577 is not acceptable here: the right behavior would be to delay the watching after the startup of the scheduler (I am sure that we have some sort of `Scheduler.on_start` function). The onlyd "difficult" point is the `unwatch` function, but I guess we could update the function in the background once this is executed.

**Comment by toots** [comment]
I believe the file will be watched after the start of the scheduler. Just pushed some changes exhibiting it. Notes:
* `file.watch` run at top-level is properly registered but you have to run the check in a `thread.run` to let the file watch a chance to run too.
* The test wasn't actually passing with the `mtime` based implementation because it polls every second. I added the proper timing to it.
* How can we write tests that run on both optional implementations?
