### ISSUE TITLE
Infallible ffmpeg encoders

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1570]
The script
```
radio = mksafe(playlist("~/Music"))
radio = ffmpeg.encode.audio(%ffmpeg(%audio(codec="libmp3lame")), radio)
output.file(%ffmpeg(%audio.copy), "radio.mp3", radio)
```
raises
```
At /home/smimram/prog/savonet/liquidsoap/libs/source.liq, line 1 char 0 - line 2 char 33:
Error 7: Invalid value:
That source is fallible
```
The error location is really bad (it corresponds to essentially nothing) and is it intended that `ffmpeg.encode` can fail even though we have an infallible source as input (note the `mksafe`)?

**Comment by toots** [comment]
This is unfortunately a limitation of the inline encoding. The ffmpeg encoding API is asynchronous, i.e. each time we push a frame for encoding, there is no guarantee that we will get encoded data out. Because of that, the current implementation uses asynchronous buffers. Another approach would be to use clocks and keep sending data until we have enough encoded data. However, this would not work with live sources and, frankly, clocks are more confusing to the users than fallible sources.

**Comment by smimram** [comment]
Ok, if there is a good reason for it, then go for it...
