### ISSUE TITLE
Timeout does not seem to be honored for process.run

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1577]
The script
```
p = process.run(timeout=2., "sleep 10")
print("Program ended: #{p.status} #{p.status.code}")
```
Exists after 10 seconds, whereas the process is supposed to be killed after 2.

**Comment by toots** [comment]
How are you testing it? This seems to work:
```ruby
set("log.level",4)

def f() =
  print("Running test program")
  p = process.run(timeout=2., "sleep 10")
  print("Program ended: #{p.status} #{p.status.code}")
end

thread.run(every=5.,f)

output.dummy(blank())
```

Logs:
```
Running test program
2021/04/18 11:12:10 [lang.run_process:4] Starting process
2021/04/18 11:12:10 [lang.run_process:4] Closing process's stdin
Program ended: timeout -1
2021/04/18 11:12:12 [lang.run_process:4] Cleaning up process
```

**Comment by smimram** [comment]
Nothing fancy on my side:
```
$ cat process.run-timeout.liq
#!./liquidsoap
p = process.run(timeout=2., "sleep 10")
print("Program ended: #{p.status} #{p.status.code}")
$ time ./process.run-timeout.liq
Program ended: exit 0
No output defined, nothing to do.

real	0m11,250s
user	0m1,148s
sys	0m0,109s
```

**Comment by smimram** [comment]
BTW, the test in `tests/language/process.liq` is passing here:
```
  p = process.run(timeout=0.5, "sleep 1")
  t(string(p.status), "timeout")
```
strange...

**Comment by toots** [comment]
That's because the timeout mechanism uses the task scheduler which isn't available if your process starts immediately at runtime.

**Comment by toots** [comment]
We could add some logs explaining that. I don't think we should raise an error.

**Comment by smimram** [comment]
Well I (and presumably other users) expected this to work. Wouldn't there be a way do ensure that?

**Comment by toots** [comment]
I believe that the case we're discussing here is very minor. It only ever happens if you need the result of the execution of a process just as your script is being processed.

Once the script has been processed, the scheduler is started and timeout mechanism works.

I expect that most reasonable use of external process happens after that phase, i.e. request resolution, API calls in `request.dynamic`, `on_track` reporting etc. That's why I suggest we just show a warning in the logs explaining that timeout is not available at the moment and how to improve it.

The reason the scheduler cannot be ran before the script is parsed is because we want to give the user the possibility to change the scheduler's settings in the script.

**Comment by toots** [comment]
I believe that this explanation and commit 1484386 took care of the issue.

**Comment by smimram** [comment]
A minor point in your explanation: `We suggest that you wrap this call in an asynchronous task.` this is not entirely clear (even to me), please provide an explanation of how to do this (at least the name of the function to call).

**Comment by toots** [comment]
Just did. I was initially reluctant to name the function in case it changes in the future.
