### ISSUE TITLE
Silently ignored parameters of encoders

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1610]
The following
```
s = playlist("~/Music")
output.file(fallible=true, %ffmpeg(format="ogg", %audio(codec="libopus", samplerate="48000", b="128k")), "/tmp/out.ogg", s)
```
fails because the `samplerate` parameter is silently ignore because it is a string and not an int (and the default samplerate of 44100 is not valid in opus). We should either `string_of_int` string parameters or at least raise an error on invalid parameters.

**Comment by toots** [comment]
Good one thanks for noticing.

**Comment by toots** [comment]
After looking, it's a bit more tricky:
* We allow for any parameter of type string/int/float:
```ocaml
    | (k, { term = Ground (String s); _ }) :: l ->
        ( match mode with
          | `Audio -> Hashtbl.add f.Ffmpeg_format.audio_opts k (`String s)
          | `Video -> Hashtbl.add f.Ffmpeg_format.video_opts k (`String s) );
        parse_args ~format ~mode f l
    | (k, { term = Ground (Int i); _ }) :: l ->
        ( match mode with
          | `Audio -> Hashtbl.add f.Ffmpeg_format.audio_opts k (`Int i)
          | `Video -> Hashtbl.add f.Ffmpeg_format.video_opts k (`Int i) );
        parse_args ~format ~mode f l
    | (k, { term = Ground (Float fl); _ }) :: l ->
        ( match mode with
          | `Audio -> Hashtbl.add f.Ffmpeg_format.audio_opts k (`Float fl)
          | `Video -> Hashtbl.add f.Ffmpeg_format.video_opts k (`Float fl) );
        parse_args ~format ~mode f l
```

This because we don't know all possible parameters.

* Also, the ffmpeg libraries know how to convert parameters types to the appropriate value.

The only reason it does not work for `samplerate` is because it is a special parameter that is not passed through the regular dictionary of ffmpeg options.

The proper fix is to allow all 3 types for this one and do the conversion ourselves. This keeps the parameter logic consistent.
