### ISSUE TITLE
clock_safe vs self_sync

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1687]
Some operators use `clock_safe` and some operators use `self_sync` for a parameter having the same effect. We should harmonize naming and use the same name everywhere.

**Comment by toots** [comment]
They are two different things:
* `clock_safe` is a static setting that indicates that the operator should be put in its own clock. This is the case for instance for `alsa` input and etc.
* `self_sync` is a dynamic setting that indicates when the operator should take control of the real-time loop. This is used for operators which require some run-time elements to control the clock, typically an active connection (`input.http` with icecast input, `input.srt`, `input.fffmpeg`, ..)

For operator where the user can specify `self_sync`, which is only `input.ffmpeg` at the moment (see: https://github.com/savonet/liquidsoap/issues/1689), we set `clock_safe` to `true` whenever `self_sync` is set to `true` unless specified otherwise because that is the most sensitive solution.

Does that clarify? How do you think we can improve the user experience with these?
