### ISSUE TITLE
Is buffer working?

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1689]
With the example
```
s = input.ffmpeg(format="lavfi", "sine=frequency=440")
output(buffer(buffer=100., s))
```
I hear the audio immediately (whereas it is supposed to buffer for 100 seconds) and moreover I hear lots of audio glitches which make it look like there is not buffer performed at all...

**Comment by dhannyz** [comment]
Hmm, I have suspected something like that has been happening with buffers too.
Also, what is the behaviour of the buffer when the source behind it goes down?
In this case I would expect it to play out the remaining 100s it has buffered, however I suspect this is not happening sometimes.
Also for input types with a 'pre-buffer' are they also affected? Again, I've noticed those buffers get flushed rather than played out.

**Comment by toots** [comment]
This looks like a `self_sync` issue. I'm not sure how to properly make it less tricky for the user but there are two cases for `input.ffmpeg`:
* The input is blocking and controls its own flow. This is the case for most of the "expected" inputs like `RTMP`, icecast etc.
* The input is not blocking and can generate as much data as you want.

Here, the input can generate as much data as you want so you need to pass `self_sync=false`, after which it works as expected.

Any idea to make this a better user experience? From a technical standpoint, this works but it seems like this is still confusing.
