### ISSUE TITLE
Use Travis

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#170]
We should try to use travis in order to check that all packages build alright:
- general doc: http://docs.travis-ci.com/user/getting-started/
- integration with OCaml: http://anil.recoil.org/2013/09/30/travis-and-ocaml.html

**Comment by dbaelde** [comment]
I like the idea. OCaml is not a problem, but all our bindings will create some extra work: the build process should first checkout the repositories for bindings, and build against them. I wouldn't put some work into it right now, since we don't have many tests besides making sure that liquidsoap builds on various versions of OCaml.

**Comment by smimram** [comment]
At least making sure that core Liquidsoap builds correctly and can execute a minimal script (and those in `scripts/tests`) would be nice...

**Comment by smimram** [comment]
Travis auto-build is now here! Leaving this open, because we should now use the tests, but they are currently failing...

**Comment by smimram** [comment]
Travis is now running with most modules and test. I encourage developpers to subscribe at least to `liquidsoap` at https://travis-ci.org/

**Comment by smimram** [comment]
(see https://travis-ci.org/savonet/liquidsoap )
