### ISSUE TITLE
Call debian packages by release name

### ISSUE THREAD

**Issue by jooola** [savonet/liquidsoap#1813]
When using `stable` and `testing` in the Debian packages filename we don't know which version of Debian it is.

Specially now that Debian stable is bullseye, it could lead to some problems.

What about using `buster` and `bullseye` in the packages file names ?

**Comment by toots** [comment]
That's a great idea. @mbugeia was saying the same. I'll do it now.

**Comment by toots** [comment]
Ok, it's done in the `main` branch. `debian_stable` is renamed to the current release codename. `debian_testing` is kept since this is always a rolling distribution (also makes it easier to not have to change the name in some places).

Docker images are now based on the latest debian stable since this could potentially bring more stability but this might change if new features are enabled that are missing on debian stable.

Thanks for reporting!
