### ISSUE TITLE
Type inference with `null()` in conditionals

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#1816]
**Describe the bug**
Nullable type inference is incorrect if I use `if-then-else-end` in wrong order

**To Reproduce**
This code sample
```
def test()
  if 0 == 0 then
    null()
  else
    1
  end
end

test()
```
will create an error
```
Error 5: this value has type
  (...) -> _?
but it should be a subtype of
  (...) -> int
```

But this code sample is ok
```
def test()
  if 0 == 0 then
    1
  else
    null()
  end
end

test()
```

The same with ternary operator.
**Expected behavior**
Allow to write `null()` in `if` in any branch.

**Version details**
 - OS: ubuntu:20.04 in docker
 - Version `2.0.0-beta.3`

**Install method**
[Liquidsoap github release deb](https://github.com/savonet/liquidsoap/releases/download/v2.0.0-beta3/liquidsoap-v2.0.0-beta3_2.0.0.beta3-ubuntu-focal-1_amd64.deb)

**Common issues**
N/A

**Comment by toots** [comment]
Good catch, thanks. The second call should be the correct one.

The problem in the first case, I believe, is that the type is fully inferred to be an `int` first and then fails to unify with `'a?` while in the other case, it is first inferred to be `'a?` and then unified with `int` to become `int?`.

I'm not sure if we can do much about it, let's see what @smimram says about this.

**Comment by smimram** [comment]
Yes, I know and have actually been hit multiple times by this one too. However, I am not sure of the correct solution. Currently, `if` is coded as a function with 3 arguments (the boolean condition, the _then_ branch and the _else_ branch), and we infer the type of arguments from right to left. This mens that if the _else_ branch is an `int`, we expect that the _then_ branch should be an `int` too and we thus fail if it is an `int?`: there is no simple way for us to backtrack and declare that the _else_ branch should actually be an `int?`.

A manual fix is to indicate that the _else_ branch should be nullable by explicitly indicating it, i.e. replace
```
def test()
  if 0 == 0 then
    null()
  else
    1
  end
end
```
with
```
def test()
  if 0 == 0 then
    null()
  else
    null(1)
  end
end
```
Or to invert the condition in order to have the `null` branch last as you suggest, i.e.
```
def test()
  if 0 != 0 then
    1
  else
    null()
  end
end
```

However, since this is quite ennoying, I could maybe add a particular case in the typechecker for this situation. Let me try to see if I can come up with something simple enough.

**Comment by vitoyucepi** [comment]
@smimram I was always interested if it's possible to set types by hand at function declaration time.

**Comment by toots** [comment]
> @smimram I was always interested if it's possible to set types by hand at function declaration time.

Type annotations are available, including for function arguments but weren't implemented for nullable types. It just got added with https://github.com/savonet/liquidsoap/commit/06d1c6d021e1845f3edb6a87e5a09ee3f710393b:
```
# def f((x:int?)) =
    if true then
      1
    else
      x
    end
  end;;
f : (int?) -> int? = <fun>

# def g() =
    if true then
      (1:int?)
    else
      null()
    end
  end;;
g : () -> int? = <fun>
```
