### ISSUE TITLE
No automatic restart after "Failed to obtain a media request!"

### ISSUE THREAD

**Issue by cgrozev** [savonet/liquidsoap#182]
Hi guys...
My icecast streams periodically shut down with "Failed to obtain a media request" as the top entry in the log, as seen below. I am still looking for the cause of this, but in the meantime wanted to ask: why doesn't the stream re-start automatically (or even does not attempt to restart), despite the fact that the default on_error parameter in the icecast.output is supposed to require that it restarts 3 secs after any error?
Any advice will be appreciated as my "going live" date is approaching fast :)

2014/06/29 06:01:37 [single:2] Failed to obtain a media request!
2014/06/29 06:01:37 [threads:1] Thread "generic queue #1" aborts with exception Cannot allocate memory in fork()!

**Comment by dbaelde** [comment]
Sorry for not responding earlier, I hope that you could fix or work around the issue. Looking at the log entry, we see that something really bad (no more memory) happens so a thread (presumably icecast) crashes. We cannot do much in such cases, except perhaps stopping liquidsoap completely instead of just the output. The real question is why the memory shortage happened, though. I'll close because the issue is old, feel free to reopen with details regarding available memory.
