### ISSUE TITLE
Is clock.assign_new prototype changed? => Error 5: this value has type   [unit] but it should be a subtype of   [source(_)]

### ISSUE THREAD

**Issue by lesion** [savonet/liquidsoap#2025]
**Describe the bug**
I'm following the example script from clocks documentation -> https://www.liquidsoap.info/doc-2.0.0/clocks.html

```ocaml
input = input.oss()

clock.assign_new(id="icecast",
  [output.icecast(%mp3,mount="blah",mksafe(buffer(input)))])

output.file(
  %mp3,"record-%Y-%m-%d-%H-%M-%S.mp3",
  input)
```

this script does not run anymore with following error:
```
➜  ~ liquidsoap test.liq
At line 4, char 2-59:
Error 5: this value has type
  [unit]
but it should be a subtype of
  [source(_)]
```

it seems that a new clock could be assigned only to a source, and this could be ok, but how we could achieve the same results of the example and decoupling latencies?
Thanks!

**Version details**
 - OS: Debian Testing
 - Version: Liquidsoap 2.0.0+git@ee13f438

**Install method**
I've tried both the release .deb package and compiling it from source.

**Comment by cdgraff** [comment]
I reach your post with the same issue, but inclusive in your example, you are not using your new clock, almost i got a warning that Source was not in use, to fix that:

```
input = input.oss()

s = clock(mksafe(buffer(input)))

output.icecast(%mp3,mount="blah",s)

output.file(
  %mp3,"record-%Y-%m-%d-%H-%M-%S.mp3",
  input)
```

**Comment by vitoyucepi** [comment]
Let me describe why this issue happened.

In 1.4.4 [`output.icecast`](https://www.liquidsoap.info/doc-1.4.4/reference.html#output.icecast) returned `active_source`, that inherited from `source`.
So it's possible to use it in `clock`.

But in 2.0.0 [`output.icecast`](https://www.liquidsoap.info/doc-2.0.0/reference.html#output.icecast) returns [`unit`](https://www.liquidsoap.info/doc-2.0.0/language.html#unit), literally nothing or `void`.
So it's not possible to use the result of `output.icecast`, because type `unit` differs from type `source`.

**Comment by toots** [comment]
Good point @vitoyucepi, gonna add something in the migration doc for this, thanks for reporting.

PS: we're planning a full rework of the clocks for `2.1.x` which should make all these things much easier to deal with.
