### ISSUE TITLE
Azuracast Auto Dj Tile not reverting back after live DJ disconnects

### ISSUE THREAD

**Issue by DJ-Lynx** [savonet/liquidsoap#2027]
Azuracast Auto Dj title not reverting back after live DJ disconnects
I found a liquidsoap code around 2 years ago that made it so when a DJ disconnects from the live stream the now playing would skip to the next song in line forcing the auto DJ metadata to reshow in stream player on website if anyone has that code or any code that can fix this issue please can you provide it because the way azuracast is at the moment when i connect my dj title comes up on the player but when i disconnect and my auto dj kicks back in the Auto dj metadata isnt there it still shows my DJ name as if im live and this is really annoying please if anyone can help me with this issue i would be really grateful as i cant find that code anywhere

**Comment by DJ-Lynx** [comment]
Anyone ?

**Comment by toots** [comment]
Do you have a script we could test? Something in isolation from the full azuracast script? Also, you might want to check with @Vaalyn who seems to be currently adapting AzuraCast to liquidsoap 2.0.0: https://github.com/savonet/liquidsoap/issues/1993

**Comment by DJ-Lynx** [comment]
I didnt install aziracast im an end user i have it from a provider but as a manager of a radio station i would really like the problem to be fixed as it really does need sorting

**Comment by SlvrEagle23** [comment]
@DJ-Lynx Please don't create issues with our upstream code providers if you're having a problem with AzuraCast in particular; it's possible that something in our configuration is causing the problem, and so it's out of their control to resolve.

Also, as a general matter of etiquette for GitHub issues, if you're an end-user working with a radio provider, it's best to take the issue up with them first, especially since they may have access to logs that you can't see from your end that could really help in the process of diagnosing the issue.

In the case of this issue, I believe we were able to resolve this issue on our end and thus this should be fixed now.

**Comment by DJ-Lynx** [comment]
Didnt know i was creting issues with upstream providers i just been asking all over the place my provider azuracast issues place liquidsoap issues place i dont knwo whos who and what the difference is and ah ok dont matter now as ive ditched azuracast in favour of a much better radi panel that just works properly ;)

**Comment by SlvrEagle23** [comment]
@DJ-Lynx There's that kindness I've come to expect from devoting 5 years of my life to building software that I give away for free.

Please close this issue if you don't mind.

**Comment by toots** [comment]
Hi all! Closing here. We're working with @SlvrEagle23 to the best of our ability to bring all the required bugfixes so that they can switch to `2.x` with all the improvements it brings as soon as possible!
