### ISSUE TITLE
Stuck at Decoding

### ISSUE THREAD

**Issue by zarza** [savonet/liquidsoap#2547]
Hello there, firstly thanks in advance for any help.

We're trying to re-stream the sound from http://icecast.zarza.com:8080/15034 to our Icecast using this:

`source = mksafe(input.http("http://icecast.zarza.com:8080/15034"))
radio = fallback(track_sensitive=false,[source])
varGenre  = "international"
varUrl    = "https://zarza.com"
varName   = "ZARZA"

output.icecast(%mp3(bitrate=128,samplerate=44100,stereo=true),
        host="icecast.zarza.com",
        port=80,
        password="hackme",
        mount = "zarza_internacionales",
        genre=varGenre,
        url=varUrl,
        name=varName,
        fallible=true,
        on_stop=shutdown,
        radio)

set("log.file",false)
set("log.stdout",true)
set("log.level",3)
`

But it got stuck at decoding. It streams but no sound is outputted. 

Any idea of how can we make this work?

We usually re-stream that signal from windows using BUTT, but we're trying to do it from Ubuntu with liquidsoap with no luck for the moment.

**Comment by vitoyucepi** [comment]
This script works for me on liquidsoap 2.1
```ruby
settings.log.stdout.set(true)

radio = input.http("http://icecast.zarza.com:8080/15034")

output.icecast(
  %mp3(bitrate=128,samplerate=44100,stereo=true),
  host="icecast",
  port=8000,
  password="hackme",
  mount="zarza_internacionales",
  genre="international",
  url="https://zarza.com",
  name="ZARZA",
  fallible=true,
  radio
)
```

I removed `fallback`, because it's useless.
Also I removed `on_stop=shutdown`, because I don't want to shutdown the whole application on source fail.

Probably you could use `fallback` with `blank` to make stream not `fallible`.
In this case if `input.http` is ok then it will be re-streamed to your icecast.
Else `blank` (silence) will be streamed, but mount point will be alive.
```ruby
radio = input.http("http://icecast.zarza.com:8080/15034")
radio = fallback([radio, blank()])

output.icecast(
  %mp3(bitrate=128,samplerate=44100,stereo=true),
  host="icecast",
  port=8000,
  password="hackme",
  mount="zarza_internacionales",
  genre="international",
  url="https://zarza.com",
  name="ZARZA",
  radio
)
```

There's also possibility to stream without re-encoding or by pulling stream with icecast directly by specifying relay options.
