### ISSUE TITLE
HLS output: set `EXTIMG` in m3u8 files  

### ISSUE THREAD

**Issue by alafanechere** [savonet/liquidsoap#2705]
The HLS output does not allow users to set an [EXTIMG](https://docs.fileformat.com/audio/m3u/) directive on the m3u8 files.
It can be useful to display cover art on players supporting this tag.

This is the content of a m3u8 file the HLS output creates:
```
#EXTM3U
#EXT-X-TARGETDURATION:2
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:35320
#EXT-X-DISCONTINUITY-SEQUENCE:1
#EXTINF:2.040,
aac_hifi_2_1666617959_35321.ts
#EXTINF:2.040,
aac_hifi_2_1666617961_35322.ts
#EXTINF:2.040,
aac_hifi_2_1666617963_35323.ts
#EXTINF:2.040,
aac_hifi_2_1666617965_35324.ts
#EXTINF:2.040,
aac_hifi_2_1666617967_35325.ts
```

**Describe alternatives you've considered**
I did not find an alternative approach

**Comment by toots** [comment]
I would suggest to use the `on_file_change` callback. It should be synchronous. If you are using on-disk files and really need precise timing, you could also move the file to a final destination.

This approach is better suited because it will allow for more flexibility. There are many possible tweaks to be done to the playlists, multiple playlists etc.

Simple implementation:
```ruby
name_of_playlist_with_extimg = "..."

def on_file_change(event, fname) =
  if event == "closed" and fname == name_of_playlist_with_extimg then
    let [first, ...rest] = file.lines(fname)
    file.write(
      data=string.concat(separator="\r\n", [first, "#EXTIMG #{image}", ...rest])),
      fname
    )
  end
end
```
