### ISSUE TITLE
`output.file` can create multiple files on reopen

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#2842]
**Describe the bug**
I've found out that sometimes `output.file` can create two different files if the file name has seconds in it. This happens because the file name function is called several times, and the current time is near the round second.

**To Reproduce**
```ruby
def file_name()
    a = time.string('/tmp/%H_%M_%S.mp3')
    print('file name is #{a}')
    a
end

output.file(
    reopen_delay=1.0,
    reopen_when={true},
    %ffmpeg(format="mp3", %audio(codec="libmp3lame", samplerate=48000, b="320k")),
    file_name,
    sine(480.)
)
```
```
2023/01/10 19:53:22 [/tmp/19_53_18.mp3:3] Re-opening output pipe.
file name is /tmp/19_53_22.mp3
file name is /tmp/19_53_22.mp3
file name is /tmp/19_53_22.mp3
2023/01/10 19:53:23 [/tmp/19_53_18.mp3:3] Re-opening output pipe.
file name is /tmp/19_53_23.mp3
file name is /tmp/19_53_23.mp3
file name is /tmp/19_53_24.mp3
2023/01/10 19:53:25 [/tmp/19_53_18.mp3:3] Re-opening output pipe.
file name is /tmp/19_53_25.mp3
file name is /tmp/19_53_25.mp3
file name is /tmp/19_53_25.mp3
```

```
#stat 19_53_23.mp3 
  File: 19_53_23.mp3
  Size: 43245     	Blocks: 88         IO Block: 4096   regular file
Device: 0,30	Inode: 69095       Links: 1
Access: (0644/-rw-r--r--)  Uid: (10000/ UNKNOWN)   Gid: (10001/ UNKNOWN)
Access: 2023-01-10 19:53:23.976039781 +0000
Modify: 2023-01-10 19:53:25.016028702 +0000
Change: 2023-01-10 19:53:25.016028702 +0000
 Birth: 2023-01-10 19:53:23.976039781 +0000
#stat 19_53_24.mp3 
  File: 19_53_24.mp3
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 0,30	Inode: 69096       Links: 1
Access: (0644/-rw-r--r--)  Uid: (10000/ UNKNOWN)   Gid: (10001/ UNKNOWN)
Access: 2023-01-10 19:53:24.012706057 +0000
Modify: 2023-01-10 19:53:24.012706057 +0000
Change: 2023-01-10 19:53:24.012706057 +0000
 Birth: 2023-01-10 19:53:24.012706057 +0000
```

**Expected behavior**
I think that between reopen tries should be exactly the `reopen_delay` time, but it drifts slightly forward.
The file name function should not be called several times.

**Version details**

- OS: `ubuntu:22.04` in docker
- Version: *2.1.3*

**Install method**
Deb package from liquidsoap releases at github

**Common issues**
N/A

**Comment by imperia777** [comment]
Hello, 
Looks like I got hit by this bug.
I am running Liquidsoap 2.4.1 (unreleased) because I wanted correct parse errors to fix my script.

A friend of mine was streaming to the radio to test it. 
At some time liquidsoap wrote another .wav file in the recordings folder. I am sure there was no connection interrupts.

> root@vdr:/mnt/data1/music/recordings/2025-11-19# ls -al
total 561968
drwxrwxrwx  2 1001  1001      4096 Nov 19 22:00 .
drwxrwxrwx 10 root users      4096 Nov 19 21:12 ..
-rw-rw-rw-  1 1001  1001 504863900 Nov 19 22:00 2025-11-19-21_12_18_JD__IVAN_DENEV_.wav
-rw-rw-rw-  1 1001  1001  70575804 Nov 19 22:06 2025-11-19-22_00_00_JD__IVAN_DENEV_.wav
root@vdr:/mnt/data1/music/recordings/2025-11-19# stat *.wav
  File: 2025-11-19-21_12_18_JD__IVAN_DENEV_.wav
  Size: 504863900       Blocks: 986072     IO Block: 524288 regular file
Device: 0,49    Inode: 98042036    Links: 1
Access: (0666/-rw-rw-rw-)  Uid: ( 1001/ UNKNOWN)   Gid: ( 1001/ UNKNOWN)
Access: 2025-11-19 22:10:49.195115063 +0200
Modify: 2025-11-19 22:00:00.094569072 +0200
Change: 2025-11-19 22:00:00.094569072 +0200
 Birth: -
  File: 2025-11-19-22_00_00_JD__IVAN_DENEV_.wav
  Size: 70575804        Blocks: 137848     IO Block: 524288 regular file
Device: 0,49    Inode: 98042048    Links: 1
Access: (0666/-rw-rw-rw-)  Uid: ( 1001/ UNKNOWN)   Gid: ( 1001/ UNKNOWN)
Access: 2025-11-19 22:16:36.139997989 +0200
Modify: 2025-11-19 22:06:40.076764862 +0200
Change: 2025-11-19 22:06:40.076764862 +0200
 Birth: -

> 2025/11/19 21:12:09 [lang:3] === CONNECTION HEADERS RECEIVED ===
2025/11/19 21:12:09 [lang:3] All headers: [("User-Agent", "Native Instruments IceCast Uplink"), ("Authorization", "Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"), ("Host", "radio.imperia.dedyn.io:xxxxx"), ("Accept", "*/*"), ("Connection", "Close"), ("Accept-Encoding", "identity;q=0.5, gzip;q=1.0"), ("content-type", "application/ogg"), ("ice-name", "JD (IVAN DENEV)"), ("ice-url", " "), ("ice-genre", "Mixed Styles"), ("ice-description", " "), ("ice-bitrate", "Quality 0"), ("ice-private", "0"), ("ice-public", "1"), ("ice-audio-info", "ice-samplerate=44100;ice-bitrate=Quality 0;ice-channels=2")]
2025/11/19 21:12:09 [lang:3] ice-name: 'JD (IVAN DENEV)'
2025/11/19 21:12:09 [lang:3] icy-name: ''
2025/11/19 21:12:09 [lang:3] name: ''
2025/11/19 21:12:09 [lang:3] SUCCESS - Stream name captured: JD (IVAN DENEV)
2025/11/19 21:12:09 [live:3] Decoding...
2025/11/19 21:12:18 [lang:3] Recording to: /mnt/data1/music/recordings/2025-11-19/2025-11-19-21_12_18_JD__IVAN_DENEV_.wav
2025/11/19 21:12:18 [switch.2:3] Switch to metadata_map.1 with transition.
2025/11/19 22:00:00 [output.file:3] Re-opening output pipe.
2025/11/19 22:00:00 [lang:3] Recording to: /mnt/data1/music/recordings/2025-11-19/2025-11-19-22_00_00_JD__IVAN_DENEV_.wav
2025/11/19 22:06:32 [live:2] Feeding stopped: Ogg.End_of_stream
2025/11/19 22:06:40 [switch.2:3] Switch to switch.1 with transition.
2025/11/19 22:06:40 [replay_metadata.2:3] Content type is {audio=pcm(stereo)}.
