### ISSUE TITLE
input.harbor.ssl and telnet

### ISSUE THREAD

**Issue by Pelican104** [savonet/liquidsoap#2966]
I had this working yesterday, but today no joy.

I'm using 2.02

I have a source set up using input.harbor.ssl it works fine, i can connect to it and stream audio.

But, it does not appear in the HELP list in telnet and I can't therefore get it's status.

```
settings.harbor.bind_addrs.set(["0.0.0.0"])
set("harbor.ssl.certificate","/etc/letsencrypt/live/REDACTED/fullchain.pem")
set("harbor.ssl.private_key","/etc/letsencrypt/live/REDACTED/privkey.pem")

live = input.harbor.ssl("live",port=8080,user="source",password="REDACTED",on_disconnect=skipy,buffer=10.0,max=20.0)
```

If i change the live source to use `input.harbor` it appears in telnet but obviously wont accept SSL connections, if I set it to `input.harbor.ssl` it accepts SSL connections but doesn't appear in telnet.

**Comment by toots** [comment]
Hi. Thanks for reporting. Would you be willing to try with the latest `rolling-release-v2.2.x` ? SSL support has been entirely rewritten there and your issue appears fixed there.

With `2.2.x`, the script would look like this:
```
transport = http.transport.ssl(
  key="/etc/letsencrypt/live/REDACTED/fullchain.pem",
  certificate="/etc/letsencrypt/live/REDACTED/fullchain.pem"
)

live = input.harbor.ssl(
  transport=transport,
  port=8080,
  user="source",
  password="REDACTED",
  on_disconnect=skipy,
  buffer=10.0,
  max=20.0,
  "live")
```

**Comment by vitoyucepi** [comment]
Hi @Pelican104,
Version *2.0.\**, including *2.0.2* you're using, will not receive updates.
But I can confirm this issue is present even in version *2.1.4*.

Anyway, it's possible to register all the required commands yourself.
You can check the documentation
- [site](https://www.liquidsoap.info/doc-2.0.2/server.html)
- [page 153 of the book](http://www.liquidsoap.info/book/book.pdf)

For example, here's how I would register the status command
```ruby
live = input.harbor.ssl(
    id="live",
    port=8080,
    user="a",
    password="a",
    "live"
)

def register_telnet_commands(_source)
  server.register(usage="#{_source.id}.status", description="Display current status.", "#{_source.id}.status", fun(_) -> _source.status())
end

register_telnet_commands(live)
```

If you are planning to interact with LiquidSoap from another process, I would recommend you use HTTP+JSON.

@toots,
For some reason `input.harbor.ssl` doesn't register default telnet commands.

This problem exists in version *2.1.4*.
1. Here's the script for liquidsoap.
   ```ruby
   settings.harbor.bind_addrs.set(["0.0.0.0"])
   settings.server.telnet.set(true)
   settings.server.telnet.port.set(8080)

   settings.harbor.ssl.certificate.set("cert.pem")
   settings.harbor.ssl.private_key.set("key.pem")

   a = input.harbor(
       id="plain",
       port=8081,
       user="a",
       password="a",
       "a"
   )
   b = input.harbor.ssl(
       id="ssl",
       port=8082,
       user="a",
       password="a",
       "b"
   )
   output.dummy(fallible=true, a)
   output.dummy(fallible=true, b)
   ```
2. Use this command to generate a key and a self-signed cert.
   `openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -sha256 -days 365 -subj '/CN=localhost' -nodes`
3. Start the luquidsoap server.
4. Connect using telnet.
   `telnet localhost 8080`
5. Execute the `help` command inside the telnet console.
6. Observe that `plain.*` commands exist, but no `ssl.*` commands.
7. Try the `plain.status` and `ssl.status` commands.

**Comment by toots** [comment]
Thanks @vitoyucepi. I recognize that this is an annoying bug. I would like to encourage all users to start moving forward to `2.2.x` and consider bug fixes in this version. This is both to save ourselves time and encourage early migration. 

If the issue is really prominent and/or troublesome, I would consider pushing a fix to `rolling-release-v2.1.x`.

**Comment by toots** [comment]
Another option is to add this to your script:
```
# @docof input.harbor.ssl
def replaces input.harbor.ssl(%argsof(input.harbor), s) =
  s = input.harbor.ssl(%argsof(input.harbor.ssl), s)

  s.on_get_ready(memoize({
    begin
      server.register(namespace=source.id(s), description="Stop current source client, if connected.",
                     "stop", fun (_) -> begin
                        s.stop()
                        "Done"
                      end)

      server.register(namespace=source.id(s), description="Display current status.",
                      "status", fun (_) -> begin
                        s.status()
                      end)

      server.register(namespace=source.id(s), description="Get the buffer's length, in seconds.",
                      "buffer_length", fun (_) -> begin
                        "#{s.buffer_length()}"
                      end)
    end
  }))

  s
end
```

**Comment by Pelican104** [comment]
Thank you both, I will use one of those solutions.
