### ISSUE TITLE
html5 video firefox stops the next video-track watching

### ISSUE THREAD

**Issue by momonosuke** [savonet/liquidsoap#312]
Hello, when I reproduce a video playlist with liquidsoap and icecast2. html5 video player in mozilla firefox, stop playing, between one video and other. You need refresh browser to watch the next video track.

apt-get install icecast2

nano playlist.pls
file1=video1.ogv
file2=video2.ogv
Save

`liquidsoap 'output.icecast(%ogg(%theora(quality=25,width=320,height=240) ,%vorbis), host = "localhost",port = 8069, password = "PASSWORD",mount = "tv-test.ogg", mksafe(playlist("playlist.pls")))'`

firefox: http://localhost:8069/tv-test.ogg

Thanks.

**Comment by toots** [comment]
Hi,

This is most likely due to an incorrect implementation of ogg playback in firefox. The way the ogg format is defined, the end of a track in the stream is just like an end of file when playing a single file. A lot of hastly implemented players do then stop there. If you really need to use that specific player, the best is then to remove all metadata using `drop_metadata` which will, in turn, generate an ogg stream with no tracks..
