### ISSUE TITLE
Video playback: excessive memory usage

### ISSUE THREAD

**Issue by sebleblanc** [savonet/liquidsoap#318]
I was testing video playback (using the GStreamer audio-video output) and left it running overnight. When I came back to my computer, I noticed that Liquidsoap was not running anymore. Looking at logs, the OOM killer was invoked after about 5 hours of playback. I have 16GB of memory on this system, so that is quite a lot of memory to use, for a simple looped video script.

Running that script for 15 minutes shows that it already uses 3.6G of resident memory, 11.4G of virtual memory.

Here is my (very simple) script:

```
background = fallback([single("./samples/videos/fireplace.mp4"), blank()])
queue = request.queue(id="request")

program = fallback(track_sensitive=false,
                   [queue, background])

output.gstreamer.audio_video(program)
```

**Comment by S54B32** [comment]
Test your script without using a fallback to blank. I have seen generating blank cause issues in the past.

It might not have any effect but worth trying.

**Comment by toots** [comment]
Is there any chance that you could try with a recent liquidsoap version compiled with gstreamer builtin (not as a plugin)? The opam install instructions should provide a quick way to get there: http://liquidsoap.fm/download.html

I'm asking b/c the bug might be fixed in the recent code and also the plugin build is now deprecated in favor of opam.

**Comment by toots** [comment]
This should be fixed now!
