### ISSUE TITLE
Add youtube live streaming.

### ISSUE THREAD

**Issue by Evreke** [savonet/liquidsoap#498]
I want to output my radio to YouTube live.
In future i plan to stream to twitch and facebook also. I found that Liquidsoap supports Youtube-dl, but no documentation on it.

Is it possible to do just with liquidsoap? Or i must use something inbetween?

**Comment by toots** [comment]
I don't think that we have this functionality right now but I'll make sure to look at it, it seems like a great feature to add.

**Comment by Evreke** [comment]
You are absolutely right. This feature may be very interesting for some users of liquidsoap. But also streaming to twitch, and facebook will be nice too.

**Comment by Lukahhh** [comment]
http://liquidsoap.info/doc-dev/protocols.html - has a brief bit of information on the youtube-dl option.

**Comment by toots** [comment]
Yeah, `youtube-dl` is for downloading. I would still love to see this feature added but I have no plans to do it myself for the moment. I'm available to mentor someone to do it, though.

**Comment by ivellios1988** [comment]
Actually there's a relatively easy solution that allows to rebroadcast our radio to YouTube.

1) You need a VPS with access to GPU or iGPU (a graphic unit integrated in the processor)

2) On your VPS, you install Ubuntu Server

3) Then you need to install a bunch of packages that will turn Ubuntu Server to Ubuntu Desktop. You will find all instructions and commands in Google

4) Then both on your VPS and PC you need to install NoMachine. It is basically a remote desktop application. Once you installed NoMachine, you need to connect to your VPS using this program

5) Tadaaaaam! Now you need to install OBS on your VPS - you will find the instructions on OBS's website

6) Open OBS, prepare some scene, add some images, etc. In order to allow yt listeners to hear your radio, you need to provide a link to your radio stream in a 'media source' element.

If your radio stream goes offline for some reason, your yt listeners will obviously hear silence. When your radio goes back online, you will need to connect to your VPS, exit OBS, launch it again and start streaming again.

And here's my solution in action: https://www.youtube.com/channel/UCWrr1yb4pR058sYZxdmjBFg/live

I rebroadcast my own radio, and on the video you see contents of a specially prepared website with a slideshow. In order to put this website in the video, I had to install a plugin called 'Linux Browser' in OBS.
