### ISSUE TITLE
not an issue but a question : switch - time scheduling with fade out/fade in

### ISSUE THREAD

**Issue by sxpdlb** [savonet/liquidsoap#550]
hello to all

this is not an issue but rather a question
My apologies if I'm not at the right place.

I want to do some time scheduling with different playlist (songs and show) and fade out + fade when the switch occurs.
I tried different coding : 

radio = fallback(track_sensitive = false, [ switch (track_sensitive=false,
                [
                        ({  0h00-10h40 }, Showplaylist),
                        ({ 10h40-10h43 }, Singleplaylist),
                        ({ 10h43-10h47 }, Showplaylist),
                        ({ 10h47-24h00 }, Singleplaylist)
                ]), security])

-> radio = fallback(track_sensitive = false
-> switch (track_sensitive=false 

Transition OK with the time schedule but hard transition (no fade out - fade in)

--------

radio = fallback(track_sensitive = false, [ switch (track_sensitive=true,
                [
                        ({  0h00-10h53 }, Showplaylist),
                        ({ 10h53-10h55 }, Singleplaylist),
                        ({ 10h55-10h57 }, Showplaylist),
                        ({ 10h57-24h00 }, Singleplaylist)
                ]), security])

switch (track_sensitive=false  (it’s the default)
Transition wait until the end of song file so the time schedule is not exactly honored. That’s not what is wanted

Any help/Idea welcome :) 
Thank you

**Comment by toots** [comment]
Hi,

You need to use the `transitions=[..]` parameter for the `switch` and `fallback`. The documentation/examples are here: http://www.liquidsoap.info/doc-1.3.3/cookbook.html, paragraph "transitions".

Please note that, if using `track_sensitive=false` transitions you might have issues where there isn't enough buffered data to trigger a transaction when the source ends. In this case, you might want to look at the relatively more complex `smart_crossfade` which has `conservative` option set for this purpose. Documentation is here: http://www.liquidsoap.info/doc-1.3.3/smartcrossfade.html

Since this is not related to code development, I'm gonna close this issue. Please, feel free to continue the conversation at savonet-users@lists.sourceforge.net
