### ISSUE TITLE
Unable to read mp3 on debian Stretch

### ISSUE THREAD

**Issue by ogomez92** [savonet/liquidsoap#562]
I am stumped.Hi all
I am running Liquidsoap Debian Stretch package which comes with 1.1.1 and I also installed the liquidsoap-lame-plugin.
However it can't read mp3 files, it says segmentation fault.
what is the issue here?
It used to work fine on Jessie.

**Comment by autonarcosis** [comment]
v1.1.1 is really old. It's best to compile v1.3.3 from the Opam. It works great on Stretch. Remember that Liquidsoap has separate Decoding and Encoding configurations. For example, it can encode MP3 but not decode (play mp3 files) because the decoder wasn't enabled (not installed/compiled in).

The MP3 decoder is MAD. The encoder is LAME.

The Opam install can be found here;
http://liquidsoap.info/download.html

**Comment by toots** [comment]
Hi! @autonarcosis is right, we only support from `1.3.x` as of now. However, if you really need to stick with `1.1.1, you should also look at `liquidsoap-plugin-mad` which should enable mp3 decoding for liquidsoap `1.1.1` on debian Stretch.
