### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by romansavrulin** [savonet/liquidsoap#563]
In a [cookbook](http://savonet.sourceforge.net/doc-svn/cookbook.html) there's a mistake in example of **Alsa unbuffered output**

The parameter `set("frame.size",940)` is incorrect and should be replaced tox `set("frame.audio.size",940)`

**Comment by hairmare** [comment]
This is fixed in the [1.3.3 cookbook](http://liquidsoap.info/doc-1.3.3/cookbook.html). The old sourceforge page is probably not getting maintained anymore, you should update your links to the new liquidsoap.info site.

**Comment by romansavrulin** [comment]
@hairmare good point, thank you. But old sourceforge page is well indexed in google and any request for API functions brings user to that page first. What links should I update in that case?

![image](https://user-images.githubusercontent.com/1313542/41215092-58959be0-6d57-11e8-8b18-725f18fdd288.png)

**Comment by hairmare** [comment]
As far as I can tell, apart from raising this issue and updating your bookmarks there really isn't much you can do.

Maybe @toots or @smimram can comment on any plans for finalising the migration to GitHub with some redirects. They would also know if there is any way you can help with that effort.

It might also make sense to cross-post this to the [savonet-users mailing list](https://sourceforge.net/p/savonet/mailman/savonet-users/) since most support usually happens there. But I'd assume my mentions above will already help this surface. 

I've already gotten used to [searching](https://www.google.com/search?q=site%3Aliquidsoap.info+input.harbor) with `site:liquidsoap.info` when I need to consult the docs 😛

**Comment by toots** [comment]
Hey! Thanks for this. I've just deleted all web content on `sf.net` and added a redirect on `index.html`. Hopefully the search engine should dereference them soon
