### ISSUE TITLE
Documentation overhault

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#571]
The documentations needs a serious overhault, in particular the language definition which is absolutely unreadable.

**Comment by gilou** [comment]
is there an easy way to include up to date doc/signatures for functions on secondary pages (not the API one) ?
I'm thinking of http://www.liquidsoap.info/doc-1.3.3/smartcrossfade.html e.g., but I noticed others as well.

**Comment by savonet-users** [comment]
We have scripts checking the syntax but that's clearly not enough.. More
eyes and hands would help a lot.

2018-08-18 6:33 GMT-05:00 Gilles Pietri <notifications@github.com>:

**Comment by savonet-users** [comment]
Feel free to drop PRs ;-)

2018-08-18 12:10 GMT-05:00 Romain Beauxis <romain.beauxis@gmail.com>:

**Comment by dikkedimi** [comment]
ehm, since I've read the cookbook today (july 7th 2021), and it mentions the 2021 updates to video encoding, should this issue from 2019 still be open? i quote: 

"Starting with the release of Liquidsoap 2.0 in 2021, the internal coding
of video changed to rgb to yuv420, which is much more compact and used by most video
libraries: Liquidsoap is now able to decently handle videos, as we will see in this chapter"

**Comment by smimram** [comment]
We now have [the book](https://www.liquidsoap.info/doc-dev/book.html) and documentation was much improved.
