### ISSUE TITLE
How to stream desktop

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#613]
How can I stream my windows desktop/audio to icecast.

I’m unsure how to open the desktop and capture it with liquidsoap. I would prefer not to use additional software.

VLC has been a PAIN, can’t connect to icecast, streams don’t load. Liquidsoap is way more powerful and reliable.

Thanks

**Comment by gilou** [comment]
For audio, if you can hook liq to the monitor it might be possible maybe with portaudio (try in() as well).

For video, that'll require more work as liq can't handle the capture afaik. Something like [OBS project ](https://obsproject.com/) might be interesting to you rather than liq. You might be able to use ffmpeg to stream it with liq, but I'm not sure how relevant that is.

**Comment by Niall7459** [comment]
Record using a device
