### ISSUE TITLE
Dynamic schedules without downtime.

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#698]
Hi, we're having a problem where making changes/adjustments to our schedule requires us to restart the liquidsoap instance. Causing listeners to drop the stream.

I have already thought about a liquidsoap behind another liquidsoap instance, but this seems impractical.

Any ideas?

**Comment by savonet-users** [comment]
There is a playlist operator reload mode = "watch" which will reload playlist if new song added or deleted. But I don't know anything like this in schedule. It will be useful if 'watch' also implemened in switch also.  
 
  On Sat, 26 Jan 2019 at 7:36 PM, Niall Lindsay<notifications@github.com> wrote:   
Hi, we're having a problem where making changes/adjustments to our schedule requires us to restart the liquidsoap instance. Causing listeners to drop the stream.

I have already thought about a liquidsoap behind another liquidsoap instance, but this seems impractical.

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
 _______________________________________________
Savonet-users mailing list
Savonet-users@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/savonet-users
  


_______________________________________________
Savonet-users mailing list
Savonet-users@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/savonet-users

**Comment by toots** [comment]
Liquidsoap to liquidsoap is a solution. Otherwise, the recommended path is to write your own scheduler and use `request.dynamic` to plug it into liquidsoap.
