### ISSUE TITLE
Live DJ Connection Not Fading Smoothly

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#746]
Hello! I've been running into this issue a bit over the last few months, and I recently attempted to fix it only to discover that I made it much worse.

The situation is a basic one: fading between the AutoDJ's music and an incoming live broadcast. I've set up a `live_enabled` switch to prevent some issues where intermittent connectivity caused DJs to fade constantly back and forth between the AutoDJ and their stream; this replaces that with a quick 2-second fallback silence for the duration they're connected:

```
live_enabled = ref false

def live_connected(header) =
  live_enabled := true
end

def live_disconnected() =
  live_enabled := false
end

# ...radio defined previously

# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id="azuratest_radio_input_streamer", port=8005, user="shoutcast", auth=dj_auth, icy=true, max=30., buffer=5., icy_metadata_charset="UTF-8", metadata_charset="UTF-8", on_connect=live_connected, on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))

live = fallback(id="azuratest_radio_live_fallback", track_sensitive=false, [live, blank(duration=2.)])
radio = switch(id="azuratest_radio_live_switch", track_sensitive=false, [({!live_enabled}, live), ({true}, radio)])
```

This is causing an abrupt jump both when the DJ connects and when they disconnect. When connecting, the AutoDJ stream immediately stops and the live DJ stream immediately starts, with no transition. When stopping, the AutoDJ starts back up again at full volume, with the live signal "fading" into the full-volume AutoDJ. Neither of these are desirable effects.

To help resolve this, I tried assigning a custom transition to the live DJ switch that performed a very simple fade:

```
def simple_crossfade(a,b) =
  add([fade.initial(duration=3.,b),fade.final(duration=3.,a)])
end

radio = switch(id="azuratest_radio_live_switch", track_sensitive=false, transitions=[simple_crossfade], [({!live_enabled}, live), ({true}, radio)])
```

...but this yields even more inconsistent results and still no smooth fading between the two.

Am I doing something obviously wrong? I get the feeling I am, but despite years of hammering away at the Liquidsoap internal language I sometimes don't feel as though I understand it.

Any help would be appreciated.

**Comment by autonarcosis** [comment]
I've been using this code I got somewhere off the site or maybe some other, can't remember.  I don't think this is would be a proper place for the simple_crossfade function.

`# Switch to Live Source when connected
# Transistion to Live source with Jingle
# Define a transition that fades out the
# old source, adds a single, and then 
# plays the new source
def to_live(jingle,old,new) = 
  # Fade out old source
  old = fade.final(old)
  # Superpose the jingle
  s = add([jingle,old])
  # Compose this in sequence with
  # the new source
  sequence([s,new])
end

# A transition when switching back to files:
def to_file(old,new) =
  # We skip the file
  # currently in new
  # in order to being with
  # a fresh file
  source.skip(new) 
  sequence([old,new])
end

# The transition to live1
djannounce = single("/home/user/Music/Radio/Jingles/YOUR DJ FOR THIS EVENING.MP3")
to_live1 = to_live(djannounce)

# Combine lives and files:
radio = fallback(track_sensitive=false, transitions=[to_live1, to_file], [live, radio]) 

`

**Comment by toots** [comment]
Hi,

You might be encountering a real issue. I've recently started auditing the transition code and I am planning some deep changes with it. In particular, I'd like to make it easier to transition with live sources.

My plan is to release the `1.3.7` bugfix shorly and review/merge the transition changes into the main branch so everybody can test it. I'll ping you when that has happened.

**Comment by gammaw** [comment]
@toots does 1.3.7 contain a fix, or did you defer it to a later release? I'm running 1.3.7 and still seeing the issue (no fading into DJ stream audio).

**Comment by gammaw** [comment]
@toots any update on this? Will this be part of release 1.4.0?

**Comment by toots** [comment]
Hi all,

I still plan to look at it although this is more of a scripting issue that a liquidsoap issue I believe.

**Comment by toots** [comment]
@SlvrEagle23 Have you tried to wrap the live source inside a `buffer` operator? I've explained a similar trick here: https://github.com/savonet/liquidsoap/issues/695 for crossfade.

**Comment by gammaw** [comment]
@toots thanks for the hint. I tried `buffer`, it didn't work for me. I think it's a bit different here than with #695 though. We'd like to fade out the AutoDJ source, switch to a live source and fade AutoDJ back in after the live source disconnected. This is my naive approach with the Azuracast config:  

```
# Fade out off air music, start playing show (without fading)
def transition_into_show(a,b)
	  sequence([fade.final(a),b])
end

# Stop show (don't fade out), fade in off air music
def transition_into_off(a,b)
	  sequence([a,fade.initial(b)])
end

radio = switch(track_sensitive=false, transitions=[ 
    transition_into_show(),
    transition_into_off() ], [ 
    ({!live_enabled}, live),
    ({true}, radio) ])

```

Fading out doesn't work, the AutoDJ stream just stops abruptly (that's my `transition_into_off` transition). Fading back in works as expected (that's `transition_into_show`). Is it maybe something with the `fade.final` function? 

@SlvrEagle23 do you have any update on this since then?

**Comment by MrLemur** [comment]
I can report I am having a similar issue trying to get a playlist to fade in after a live stream disconnects.

**Comment by toots** [comment]
Any chance someone could test this with the latest `1.4.3-prelease`? Build should be here: https://github.com/savonet/liquidsoap/releases/tag/v1.4.3-pre-release

**Comment by SlvrEagle23** [comment]
AzuraCast users: this fix has been integrated into our Docker installation images so you can test and verify that it's fixed.

**Comment by toots** [comment]
Crossfading with live content is tricky. Here are a couple of notes:

* `fallback` and `switch` transitions may not able to retain much data for the ending source. The reason lies in the logic: if there are `track_sensitive=true`, the transition is triggered on track end, thus there is no more data for the ending source. In case of a `track_sensitive=false`, though, this should have a little more.
* However, for complex transition situation, I think it's good practice to use `cross`/`crossfade` as there is much more extensive work done there. `fallback` and `switch` transitions should be reserved for simple cases in my opinion. 
* Crossfading with live content requires that you buffer the crossfaded data ahead of time as this will have to be pulled faster than real-time

Here's an implementation that should work in your situation. The `6.` buffer should hopefully help with clients with intermittent connections as well:
```
# Live Broadcasting
live = audio_to_stereo(input.harbor("/")

# Tag live, used to detect transitions from/to live
def tag_live(_) =
  [("type","live")]
end
live = map_metadata(tag_live, live)

# Add 6. buffer, the time for fade.in + fade.out
live = buffer(buffer=6., fallible=true, live)

# Combine live and radio
radio = fallback(track_sensitive=false, [live, radio])

# Custom transition, crossfading from/to live and
# keeping normal track transitions otherwise.
def transition(a,b,ma,mb,sa,sb) =
  if ma["type"] == "live" or mb["type"] == "live" then
    log("Transition from/to live: crossfading..")
    add(normalize=false,[fade.in(duration=3.,sb), fade.out(duration=3., sa)])
  else
    sequence([sa, sb])
  end
end

radio = cross(transition, radio)
```

I'm gonna take this issue out of the `1.4.3` release schedule as it seems more like a usage question than a bug. Feel free to let us know otherwise.

**Comment by SlvrEagle23** [comment]
Note for AzuraCast users: As of today's commits, this functionality is now a part of AzuraCast's rolling-release image. Thanks to Romain for the code samples and for working with me to help solve this issue.

**Comment by dvdokkum** [comment]
Just tested this a bit via the rolling-release in AzuraCast mentioned above.... specifically [this commit](https://github.com/AzuraCast/AzuraCast/commit/51a229280390b9e6562e4936430364e12ce3d7ad) on `v0.10.3, #51a2292 (2020-08-02 17:32) Rolling • Docker • PHP`.

The signal would crossfade back and forth between the AutoDJ and the livestreamer and never fully switch over to the livestreamer. This was with a 15s buffer configured for the streamer. I upped the buffer to 30s but got the same behavior. Had to disable crossfading entirely in AC in order to get a full transition over to the livestreamer.

**Comment by ajeje989** [comment]
i have the same problem with client with bad internet i have sonicpanel

u have idea ?
