### ISSUE TITLE
CPU / Memory use for basic icecast streaming ("ezstream use-case")

### ISSUE THREAD

**Issue by joannahaiden** [savonet/liquidsoap#748]
Have very basic icecast streaming requirement constantly stream a MP3 playlist, that is it.  Nothing else fancy.   ezstream has been working well for years, but it seems dead development-wise, and is clunky if you want several streams.

I have created a liquid soap script that streams the same content, but where my ezstream source would sit about 0.3% CPU use on my RaspberryPi B+, Liquid soap sits about 30% CPU use, and about 10x the memory footprint.

My script is such:

#!/usr/bin/liquidsoap

out = output.icecast(%mp3,host="localhost",password="hackmetobits", description="My Rockbox", url="http://myurl/gm", public=false, genre="Rock", mksafe(playlist("/media/playlist.m3u")), mount="gm" ) 

Any advise?  Other than stick to ezstream?  Is LiquidSoap too bloated for my use requirements?

**Comment by autonarcosis** [comment]
I suspect your ezstream setup isn't re-encoding it's output.  Liquidsoap is decoding, then re-encoding based on your output settings. It can also encode to multiple formats simultaneously quite easily. This is where a substantial amount of CPU time is used.  Memory usage is due to the playlists are loaded into memory and it's a vastly larger program with a lot more functionality than ezstream. Large playlists will consume more memory.  You'll have to decide on whether you want the massively increased functionality over the resources it uses.

**Comment by savonet-users** [comment]
On Sat, 6 Apr 2019, 14:59 joannahaiden, <notifications@github.com> wrote:

> Have very basic icecast streaming requirement constantly stream a MP3
> playlist, that is it. Nothing else fancy. ezstream has been working well
> for years, but it seems dead development-wise, and is clunky if you want
> several streams.
>
> I have created a liquid soap script that streams the same content, but
> where my ezstream source would sit about 0.3% CPU use on my RaspberryPi B+,
> Liquid soap sits about 30% CPU use, and about 10x the memory footprint.
>
Maybe worth checking for unwanted sample rate conversions, and the way the
MP3 encoder is set up? I'm on an ancient x86_64 GNU/Linux box and LS merely
sips CPU.

J

>
>

**Comment by joannahaiden** [comment]
> I suspect your ezstream setup isn't re-encoding it's output. Liquidsoap is decoding, then re-encoding based on your output settings. It can also encode to multiple formats simultaneously quite easily. This is where a substantial amount of CPU time is used. Memory usage is due to the playlists are loaded into memory and it's a vastly larger program with a lot more functionality than ezstream. Large playlists will consume more memory. You'll have to decide on whether you want the massively increased functionality over the resources it uses.

I can cope with the memory footprint increase.  However the decoding/encoding seems totally unwanted, all the songs in the playlist are already in the correct format, bitrate (as I encoded them all), is there any way to force it to just stream as-is?

**Comment by autonarcosis** [comment]
I am not aware of LS to stream the playlist content as-is. As far as I understand it, that is not how it works. It decodes the playlist files (which can be various formats) into a raw format, then based on the output configuration sends that raw data to encoders (internal or external) or physical hardware.  This is how it achieves the ability to cross fade, overlays and other features.

**Comment by toots** [comment]
Hi,

Unfortunately, Liquidsoap cannot work with compressed formats. That's the price to pay for the flexibility that it provides, as @autonarcosis put it well.

I'm closing this issue since I don't think that we can do much about it. You can, however, look a the `%shine` encoder if you want to reduce CPU/memory footprint for mp3 encoding.

**Comment by sripwoud** [comment]
For anyone landing here from search — some concrete numbers for exactly this use-case (mp3 playlist → icecast, `playlist` → `crossfade` → `mksafe` → `output.icecast(%mp3(bitrate=128))`), measured on liquidsoap 2.3.2 / Debian 13 via cgroup `memory.current`/`memory.stat`, not RSS:

| scenario | total | anon heap |
|---|---|---|
| 1 stream, 1 h uptime | 556 MB | 439 MB |
| 2 streams, 13 min | 531 MB | 448 MB |
| 2 streams, 13 min, `OCAMLRUNPARAM=o=40` | 205 MB | 164 MB |

Two observations that would have answered my own questions:

- The footprint is dominated by the runtime, not per-stream encoding: a second stream added ~10–50 MB. If you left ezstream because multiple streams were clunky, liquidsoap amortizes well.
- OCaml's default GC `space_overhead=120` accounts for most of the gap: bounding it (here via the `OCAMLRUNPARAM` env var in the systemd unit) cut memory 2.7× with no audible effect. This is now officially documented in the [memory management guide](https://www.liquidsoap.info/doc-dev/memory.html), which postdates this issue — linking it here since this thread ranks well in search.

**Comment by toots** [comment]
> For anyone landing here from search — some concrete numbers for exactly this use-case (mp3 playlist → icecast, `playlist` → `crossfade` → `mksafe` → `output.icecast(%mp3(bitrate=128))`), measured on liquidsoap 2.3.2 / Debian 13 via cgroup `memory.current`/`memory.stat`, not RSS:
> 
> scenario	total	anon heap
> 1 stream, 1 h uptime	556 MB	439 MB
> 2 streams, 13 min	531 MB	448 MB
> 2 streams, 13 min, `OCAMLRUNPARAM=o=40`	205 MB	164 MB
> Two observations that would have answered my own questions:
> 
> * The footprint is dominated by the runtime, not per-stream encoding: a second stream added ~10–50 MB. If you left ezstream because multiple streams were clunky, liquidsoap amortizes well.
> * OCaml's default GC `space_overhead=120` accounts for most of the gap: bounding it (here via the `OCAMLRUNPARAM` env var in the systemd unit) cut memory 2.7× with no audible effect. This is now officially documented in the [memory management guide](https://www.liquidsoap.info/doc-dev/memory.html), which postdates this issue — linking it here since this thread ranks well in search.


thanks for looking into this! I would advise to check against `2.4.5` as there were a bunch of important optimizations regarding GC allocated data that went out with that release. With this version and in `main` too, the script should allocate much less transient memory.
