### ISSUE TITLE
[Question] Simultaneous voice + playlist with transitions

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#753]
(I got dmarc errors while sending this message to the mailing list, reposting in case it got lost) 

I'm doing a live radio. One of the requirements is to be able to play the voice input with a playlist running in the background. When the voice is active, the playlist should be at a lower volume, otherwise it should be at full volume. 

For an example, you can listen the start of https://www.radiokawa.com/episode/les-tauliers-85/. It starts with a pre-recorded track, followed by the live voice at 00:20. The background track fades out after a few minutes. The same goes in reverse at the end. Note that some shows don't do that and simply wait for the end of the track to start the voice, without negative gain. 

Current simplified setup : 
``` 
voice = switch([(interactive.bool("voice_active"), in()]) 
tracks = request.queue() 
out(add([voice, tracks])) 
``` 
I use a python controller to set voice_active and push tracks to the queue when needed using on_end. 

- How can I do the amplification transition? 
- Should I use request.dynamic instead ? My main concern is how to handle the case where there is no track to play. Maybe return `fail()` at the end of the playlist + use `source.skip` when I want to start the next track? 

BTW, I'm doing the new live broadcast system for radiokawa.com, first public test in weeks. I couldn't have done that without liquidsoap. I can ping you if you want !

**Comment by toots** [comment]
Hi,

You can look at `smooth_add` for that purpose. There's an example here: https://www.liquidsoap.info/doc-1.3.6/cookbook.html

If you want to explore and hack further, in the current `master` branch, which will eventually come out as version `1.4.0`, there's a full rewrite of fade operators, including `smooth_add`.

Essentially, `amplify` can now take a `()->float` callback, which you can use to define whatever fading function you wish. 

However, since source's timing is not real time, you need to use `source.time` to keep track of the source's local time. The typical example being: https://github.com/savonet/liquidsoap/blob/master/scripts/fades.liq#L7

I'm closing this for now, let us know if you need more info or have any success with it. Thanks for the encouragements as well!

**Comment by Yamakaky** [comment]
Hum, I missed this section of the doc, I'll try it ^^

First episode out, we added a Thanks to liquidsoap at the beginning ;) https://www.radiokawa.com/episode/nawak-1/

BTW, do you prefer to have these questions as issues or via the mailing list ? (BTBTW, did you get this question via the mailing list ? ^^)

**Comment by Yamakaky** [comment]
Works fine, thank you!

**Comment by toots** [comment]
Awesome!

**Comment by toots** [comment]
As for questions, we're still debating it. cf: #752. For now, all issues go to the mailing list so feel free to ask some here with the gotcha that we may close the issue and let the conversation happen through the messages.

Long term, I'd like to get rid of the mailing list, at list as a sourceforge hosted service since that is our last tie over there.
