### ISSUE TITLE
ALSA output goes silent after some time

### ISSUE THREAD

**Issue by GermanCascales** [savonet/liquidsoap#755]
**Describe the bug**
Hi everyone! I've seen some similar issues here but still cannot fix this. I'm using Liquidsoap in order to relay a stream through the audio driver. Everything works good until after 24 hours more or less the audio stops. The process still runs and log doesn't show any error and continues loading new songs metadata from Icecast. I've been trying this on another Raspberry Pi 3 B+ using repository's LS 1.1.1 and the same problem happens but failing after around 6 hours.

If I restart the service, it works again normally for another period of time.

**To Reproduce**
Attached my script: set it up to run it at startup using liquidsoap-daemon. Besides a Behringer UCA202 USB soundcard, I have also tested this using the built-in RPi 3.5mm jack output, both with same result.

```
set("log.level",5)

main_url = "xxx"
emergency_audio = playlist(mode="randomize",reload=1,reload_mode="rounds","/home/pi/Music")

def crossfadeEmergency(t,a,b)
  add(normalize=false,
          [ sequence([ blank(duration=t/2.),
                       fade.initial(duration=t,b) ]),
            fade.final(duration=t,a) ])
end

def crossfade(t,a,b)
  system("/home/pi/notify.py &")
  add(normalize=false,
          [ sequence([ blank(duration=t/2.),
                       fade.initial(duration=t,b) ]),
            fade.final(duration=t,a) ])
end

radio_stream = input.http(main_url)

emergency_audio = mksafe(emergency_audio)

radio_stream = fallback(track_sensitive=false, transitions=[crossfade(.4),crossfadeEmergency(.3)], [strip_blank(max_blank=60.,radio_stream), emergency_audio])

output.alsa(device="hw:CARD=CODEC", radio_stream)
```

**Version details**
 - OS:  Raspbian GNU/Linux 9.8 (stretch)
 - Version: Liquidsoap 1.3.6

**Install method**
Installed it via opam 2.0.3.

Thanks a lot for your help!

**Comment by autonarcosis** [comment]
Quick testing and got about 15 hours in before it stopped working for me. LS completely stopped output inthe log files.  I forgot to test the telnet harbor before killing the process. Using Fedora, ALSA v1.1.8,,  AMD Athlon X2 cpu and ALC888 sound on motherboard.

**Comment by autonarcosis** [comment]
I've been continuously testing ALSA output and, it's been solid ever since I restarted the process.

The only difference I can think of between when it initially stopped working and now is;  I believe Sunday evening, weekly cron jobs are activated. Specifically pretty cpu/ram intensive ones such as webalizer.

Check for something like this, are cron jobs being triggered that causes CPU/RAM usage to spike and such that would cause massive buffering or even disk access. 

Try testing out the ALSA settings in LS and use the --debug command option to see if you can get more information on what is occurring.  Possibly setting the frame buffer higher perhaps? Links to ALSA settings;

https://www.liquidsoap.info/doc-1.3.6/settings.html
https://www.liquidsoap.info/doc-1.3.6/cookbook.html

Another suggestion is to try playing the source using an alternative method such as ffplay to test the ALSA output.  It would be something like;

`$ SDL_AUDIODRIVER="alsa" AUDIODEV="hw:1,0" ffplay -i urltosource`

Sorry couldn't be more helpful.

**Comment by GermanCascales** [comment]
Thank you so much for your help and of course for all your tests, @autonarcosis 

I will try and check all your suggestions, but I must say that in a moment of despair, without knowing what else I could do, I tried bringing the LS script to a minimum, not even using the daemonizer tool.

```
set("log.file",true)
set("log.file.path","/home/pi/logprueba.log")
set("log.level",5)

security = single("~/Music/emg.mp3")

radio = fallback(track_sensitive = false, [input.http("xxx"), security])

output.alsa(device="hw:CARD=CODEC", radio)
```

This script has been running smoothly for about a week. Not a single stop to silence. I will continue testing of course, because this script doesn't take advantage of all the potential that Liquidsoap could offer me in its full operation 😢

Thanks again for being so helpful!

**Comment by toots** [comment]
Hi,

Are you able to test the latest `master` branch? It contains a whole rewrite of transitions that could potentially fix this issue. If you're using `opam` you can just do:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add .
```

**Comment by GermanCascales** [comment]
> Hi,
> 
> Are you able to test the latest `master` branch? It contains a whole rewrite of transitions that could potentially fix this issue. If you're using `opam` you can just do:
> 
> ```
> git clone --recursive https://github.com/savonet/liquidsoap.git
> cd liquidsoap
> opam pin add .
> ```

I've been testing the latest version from GitHub as you advised me, and it works like a charm! 11 days with the first script and still not silent. Thank you so much!!

**Comment by toots** [comment]
Awesome! Closing this one!
