### ISSUE TITLE
Liquidsoap exits with "Fatal error: out of memory." error

### ISSUE THREAD

**Issue by scooper91** [savonet/liquidsoap#877]
We're seeing occurrences of Liquidsoap crashing (exit code 2) with the error `Fatal error: out of memory.`.  Memory usage, CPU, etc all looked fine, and there were no spikes at or before the crash.

We haven't been able to reproduce it.  We have 40 Liquidsoap instances (completely separate), and after about a week of being up, a couple of the instances will crash.

Liquidsoap is running in it's own docker container, and runs on the container using supervisord. The tracks are being queued from another container, using the socket.  The tracks are put into a mounted volume when the app starts (and when the playlist loops, if the tracks aren't there already).

We only ever have two tracks in the queue at one time (when one has finished playing, we add another track to the queue). The tracks are around 5 MB each. It loops tracks infinitely (about 400-500 unique tracks).

`play.liq` config:
```
set("log.file", false)
set("log.stdout", true)
set("log.level", 3)

set("server.socket",true)
set("server.socket.path", getenv("SOCKET_DIR") ^ "/play.sock")

output.icecast(
   %mp3(bitrate=320, samplerate=48000, stereo=true),
   id = 'source1',
   host = 'icecast',
   port = 8000,
   password = 'xxx',
   mount = 'radio.320',
   name = getenv("STREAM_NAME"),
   mksafe(
      smart_crossfade(
         start_next=3.0,
         fade_in=2.0,
         fade_out=2.0,
         request.queue(id="radio_queue")
      )
   )
)
```

Logs just prior to the crash:
```
2019/07/10 07:59:45 [decoder:3] Unable to decode "/home/liquidsoap/track-cache/282595.mp3" as {audio=2;video=0;midi=0}!
2019/07/10 07:59:45 [server:3] Client unix socket "" disconnected without saying goodbye..!
2019/07/10 07:59:50 [server:3] New client unix socket "".
2019/07/10 07:59:50 [server:3] New client unix socket "".
2019/07/10 07:59:50 [server:3] Client unix socket "" disconnected.
2019/07/10 07:59:50 [server:3] New client unix socket "".
2019/07/10 07:59:50 [server:3] Client unix socket "" disconnected.
2019/07/10 07:59:50 [decoder:3] Method "MAD" accepted "/home/liquidsoap/track-cache/69370920.mp3".
2019/07/10 07:59:50 [server:3] Client unix socket "" disconnected.
Fatal error: out of memory.
2019-07-10 07:59:50,849 INFO exited: liquidsoap (exit status 2; expected)
```
RE the `Unable to decode` message a few seconds before the crash. We did not see that error the previous time Liquidsoap crashed (I think the error is because we gave Liquidsoap a corrupt file).

We use the socket to check what's playing and queued (every 5 seconds).

**Version details**
 - OS: debian:buster-slim (docker)
 - Liquidsoap Version 1.3.3

**Install method**
Installed using `apt-get`

**Comment by toots** [comment]
Hi,

Thanks for the report. This error is expected in extreme cases where the software cannot allocate new memory through a call such as `malloc`.

Due to the low-level nature of this issue, as well as the container context, I am marking it as `cannot reproduce` for now. Please don't mistake that for not wanting to fix it!

I think that, in order to trace the issue we would need to at least try to get a backtrace of the exception. I believe that `gdb` is probably the best tool here.

Do you think that you would be able to run the script through a `gdb` instance and return a backtrace? In a normal setting, you would do:
```
% cat /tmp/commands
run <args>
thread apply all bt
% gdb gdb -batch -x /tmp/commands /path/to/liquidsoap
```
`/tmp/commands` contains the list of commands for `gdb` to run. In this case, the process should return a backtrace when it crashes.
