### ISSUE TITLE
Issue with on_blank when new connection on input.harbor

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#884]
**Describe the bug**
I use `strip_blank` to disable a `input.harbor`, so that a user can connect to the server before the live with his microphone muted to test the connection without outputting junk audio online. Since only silence is streamed, I would expect the input to never become activated while the microphone stays muted.

**To Reproduce**
Use `butt` for example as harbor client.
```
$ liquidsoap 'output.dummy(fallible=true, strip_blank(max_blank=5.0, start_blank=true, input.harbor("input")))
...
2019/07/19 16:35:49 [dummy:3] Source failed (no more tracks) stopping output...
2019/07/19 16:35:59 [decoder:3] Method "MAD" accepted "audio/mpeg".    <--  Connecting
2019/07/19 16:35:59 [input(dot)harbor_7091:3] Decoding...
2019/07/19 16:36:06 [dummy:3] Source failed (no more tracks) stopping output...   <- 5s later
...
```

**Expected behavior**
I would expect `dummy` to stay failed. Not sure if the issue is the issue is in `butt`, `start_blank` or `input.harbor`.

**Version details**
 - OS: alpine
 - Version 1.4.0+scm (https://github.com/savonet/liquidsoap.git@e1d0cf2f20cc0727e683610e44cf8d4af98ee02f:20190719:140506)

**Comment by toots** [comment]
Thanks for the report. It underlined an issue in the code so I'm happy you pointed out. However, it is important to remember that, for now, in order to make sure that we don't miss audio at the beginning of tracks, all blank operators reset their state on new tracks. We could change this behavior but I'm not sure that I see a pressing need for it.

**Comment by Yamakaky** [comment]
Naisu!
