### ISSUE TITLE
Stereo Tool resets/restarts on each track

### ISSUE THREAD

**Issue by RM-FM** [savonet/liquidsoap#885]
Stereo Tool resets/restarts each time a new track begins to play. As a consequence there are ugly crackles and volume „jumps“. As a workaround „drop_metadata“ helps.

Important: We are using crossfade().

As far as I remember there was a similar issue reported for version 1.3 as well back in the days. It was related to some header data.

**Version details**
 - OS: Ubuntu 16.04.6 LTS
 - Version: Latest 1.4.0 beta

**Install method**
- opamng

**Comment by toots** [comment]
Hi,

Thanks for reporting. This is a complex issue. The first problem is that, when pipping data through an external application, it is not easy to track the timing of the outgoing data. For this reason, the only way to be able to re-inject the input's metadata into the output is to close the pipping process, flush all pending data and then add the metadata. This is the reason why stereo tool is closed on each metadata.

The first question is: why is stereo tool creating crackles and volume jumps? Does the tool need to work across tracks to create a smooth experience? Would it be different if you were to, say, pre-process all tracks ahead of streaming them?

If pre-processing the tracks is an option then we could create a stereo tool protocol that would take care of the during the request resolution so you don't have to rely on `pipe`.

Otherwise, if you need to work across tracks, then I will suggest to place stereo tool last in the script, just before the output and to drop all metadata and tracks. But in this case, we'd have to think about how to send them through a different, off the band, channel.

**Comment by RM-FM** [comment]
We've already tested offline sound processing on each file. Unfortunately the transitions often sound very harsh. With real-time audio processing, crossfades sound much nicer and smoother.

Actually it is not a big deal to drop the meta data before looping-in Stereo Tool. But we should be able to set them again after processing. Of course it would be great to have an adjustable delay as well, but I guess we could also live without it as the processing delay is quite small.

Is there any way to achive this?

**Comment by smimram** [comment]
Here is my take on this, you will need the `on_frame` command added in https://github.com/savonet/liquidsoap/pull/886.

The resulting script is as follows. Basically, I drop the metadata, process the audio, and then reinsert the metadata. The re-insertion is only precise up to a frame, which should not be so bad.
```
def map_without_metadata(f, s)
  has_meta = ref.make(false)
  meta = ref.make([])
  def f_meta(m)
    ref.set(has_meta, true)
    ref.set(meta, m)
  end
  s = on_metadata(f_meta, s)
  s = drop_metadata(s)
  s = merge_tracks(s)
  s = f(s)
  let (insert, s) = insert_metadata(s)
  def f_frame()
    if ref.get(has_meta) then
      insert(ref.get(meta))
    end
    ref.set(has_meta, false)
  end
  on_frame(f_frame, s)
end

s = playlist("~/Music/misc")
s = chop(duration=2., metadata=[("title", "test")], s)

s = map_without_metadata(pipe(process="ffmpeg -i - -f wav -"), s)

s = on_metadata(fun(_) -> print("GOT METADATA!"), s)

s = mksafe(s)
out(s)
```
Let's hear what @toots thinks of this :)

**Comment by gilou** [comment]
I need to test it on 1.4.0 but I'm not sure what's being tested here. I don't use pipe as I want the medadata to go out on purpose, and use output / input.external rather than pipe() but until now, it worked flawlessly...

**Comment by smimram** [comment]
You can use the same trick with external i/o:
- use `on_metadata` to capture the metadata of the source,
- use `drop_metadata`and `merge_tracks` to remove tracks (you can also play with the `repen_on_metadata` parameter of `output.external`)
- use `insert_metadata` after the `input.external` to get a way to register metadata
- use `on_frame` to call metadata insertion if needed after every frame

Is it more or less clear?

Something that I don't understand: do you claim that it used to work in < 1.4.0  and the bad behavior is new in 1.4.0?

**Comment by gilou** [comment]
I claim that I use something like : https://gist.github.com/gilou/43133d2619202791e153211471aff6a1#file-functions-liq-L115
on liq 1.3.7

which is basically:
```
# feeding back the stream to liq
pipe_input = mksafe(input.external("(test -p #{pipe_file} || mkfifo #{pipe_file}) && cat " ^ pipe_file))
# send to st
cmd = '/usr/local/bin/stereo_tool_cmd_64 -q - ' ^ pipe_file
stereo_tool = output.external(id="st", %wav, cmd, source)
```

And that it works fine without dropping metadata (and you can see I use somehow the trick you mention to get the metadata back, but that's not the point), and stereotools works fine (as did ffmpeg / sox when we debugged this a while back with @toots 

I'll try if it broke in 1.4.0 but I'm not there yet...

**Comment by RM-FM** [comment]
@gilou I'd like to understand your piece of code. Would it be possible to provide a short but working example starting with the unprocessed source and ending with the processed source? That would be great.

@smimram I gave `map_without_metadata` a try. Unfortunately, LS doesn't start and reports error: Undefined variable `on_frame`

**Comment by smimram** [comment]
Concerning my proposal, you need the [`on_frame` branch](https://github.com/savonet/liquidsoap/pull/886) to have the `on_frame` function.

**Comment by RM-FM** [comment]
@smimram Works :-) Great job!

**Comment by gilou** [comment]
> @gilou I'd like to understand your piece of code. Would it be possible to provide a short but working example starting with the unprocessed source and ending with the processed source? That would be great.

I'll elaborate on the code I gave earlier, but again, if I can use pipe() and keep the metadata, I'll switch hehe.. I can't just follow all the beta versions on my setups, I use opam, and don't do repos pinning on my automated workflow, so there's that.

```
# feeding back the stream to liq
pipe_file = '/tmp/some_pipe'
# dummy source
s = sine()
# overly complicated to just create the named pipe if it doesn't exist, and use cat to read from it
pipe_input = mksafe(input.external("(test -p #{pipe_file} || mkfifo #{pipe_file}) && cat " ^ pipe_file))
# send to st through stdin, which sends back on the pipe
# whatever params you need for stereo_tool
cmd = '/usr/local/bin/stereo_tool_cmd_64 -q - ' ^ pipe_file
stereo_tool = output.external(id="st", %wav, cmd, s)
output.icecast( %mp3, mount='test_st', pipe_input)
# listening to /test_st clearly is going through st, if you don't put a license file you'll hear the beeps :P 
```

**Comment by toots** [comment]
Hi guys,

@gilou's code amounts to dropping metadata since the `%wav` code does not encode metadata.

Regarding re-adding metadata, I think the problem here is that the encoding binary, here `stereo_tool` might keep an internal buffer of data that we have no knowledge of. Re-adding metadata like that will work but it will add the metadata at points that are potentially very out of sync.

I don't like `on_frame` personally because it relates to internals of the software. At the very least, I'd consider naming it `on_tick` which would relate bette to the internal loop and would sound more natural for e.g. people with javascript background.

But, before we proceed, is there a chance that @RM-FM could test Sam's PR and tell us how out/in sync the re-added metadata get?

**Comment by toots** [comment]
@RM-FM to try sam's branch:
```
cd /path/to/liquidsoap/git
git fetch && git checkout on_frame
opam reinstall -y .
```

**Comment by RM-FM** [comment]
@toots It depends on the latency/buffer settings of Stereo Tool. In our case (max. latency => highest quality) it's approx. 11 seconds offset (meta update too early).

**Comment by smimram** [comment]
I guess that we could even delay metadata re-insertion :)

**Comment by toots** [comment]
Yeah I think this is the right solution, I'm gonna implement an alternative mode which doesn't reload the tool in track/metadata but re-inserts them with a fixed delay instead.

**Comment by smimram** [comment]
I was thinking about how to modify my implementation in order to achieve this delay. The obvious answer is to use `add_delay`, which would not be very precise. However, we could add a variant of `add_delay` which would take a source as argument, and where the time reference would be the time flow of the source, which would solve the problem. What do you think of it?

**Comment by smimram** [comment]
To be more precise, this is what I have in mind:
```
def map_without_metadata(~metadata_delay=10., f, s)
  has_meta = ref.make(false)
  meta = ref.make([])
  def f_meta(m)
    def f()
      ref.set(has_meta, true)
      ref.set(meta, m)
      (-1.)
    end
    add_timeout(metadata_delay, f)
  end
  s = on_metadata(f_meta, s)
  s = drop_metadata(s)
  s = merge_tracks(s)
  s = f(s)
  let (insert, s) = insert_metadata(s)
  def f_frame()
    if ref.get(has_meta) then
      insert(ref.get(meta))
      ref.set(has_meta, false)
    end
  end
  on_frame(f_frame, s)
end

s = playlist("~/Music/misc")
s = chop(duration=2., metadata=[("title", "test")], s)
s = map_without_metadata(pipe(process="ffmpeg -i - -f wav -"), s)
s = on_metadata(fun(_) -> print("GOT METADATA!"), s)
s = mksafe(s)
out(s)
```

**Comment by toots** [comment]
`source.time` is probably a good start in this case since a source's local time isn't necessarily the computer's global time. 

In this very case, however, I'm in favor of implementing the feature in the operator since it's a feature a lot of users will want out of the box.

**Comment by RM-FM** [comment]
For some reason this happens even without meta data. According to the log, the pipe is closing with response code „0“ and then gets restarted immediately.

**Comment by toots** [comment]
The process will also restart on new track marks, in which case you can use `merge_tracks`

**Comment by sonyarianto** [comment]
Thank you for the `replay_delay` addition on `pipe`, for other people that experience the same problem, here is the example to avoid volume jumps during track changes on piping with Stereo Tool.

```
final = pipe(replay_delay=1.0, process='/stereo_tool_cmd_64 - - -s /config.sts -q -k "YOUR_STEREO_TOOL_LICENSE"', songs)
```

So far it works for me :)
