### ISSUE TITLE
HLS: In-Playlist Timed Metadata

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#916]
This might be an easier place to start for communicating live/dynamic metadata in HLS.
This is a more recent addition, and should be much more simple for liquidsoap to insert as it is just extra tags in the m3u8 playlists. However it may require using a higher x-version where liquidsoap is currently using `#EXT-X-VERSION:3`

https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.7

I believe this would also require setting #X-PROGRAM-DATE-TIME tags for proper timings

**Comment by dhannyz** [comment]
I believe this would also require setting #X-PROGRAM-DATE-TIME tags for proper timings

**Comment by Diman779** [comment]
Метаданные р
Появились  ?

**Comment by toots** [comment]
I'm looking at this. Would love to add it as soon as I find out what the payload is supposed to look like..

**Comment by cdgraff** [comment]
+1 really important feature to all Media World, Dynamic Ads insertion depends of this capabilities

**Comment by RobinvdGriend** [comment]
@toots: I think [this section in the spec](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.2) shows how the payload looks like. It should be a simple comma-separated list in the tag itself right? Is there a way right now to hook into the HLS-segmenter to add these tags somehow?

**Comment by toots** [comment]
This was fixed with #3153 for in-stream ID3 metadata and #2898 for `#X-PROGRAM-DATE-TIME` support.

As far as I can see from the spec, the list of tags supported by `#X-PROGRAM-DATE-TIME` by default is mostly geared toward ad insertion with the capacity to include user-defined custom tags. What we are mostly concerned with by default is media metadata, `title`, `album` etc.

From our perspective, it makes more sense to consider that an advance use and to expose callbacks to allow users to insert arbitrary tags in order to give them full control over this feature.

On the contrary, in-stream ID3 metadata provide a standard way of adding media metadata so these are enabled by default.

Hopefully this gives everyone a chance to do whatever they are trying to do with HLS!
