### ISSUE TITLE
Feasibility study: convert non-required encoders params to support variables.

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#936]

**Comment by smimram** [comment]
This is actually implemented in #939, isn't it?

**Comment by smimram** [comment]
Honestly, I don't really believe we can do something like that because this means that some evaluation should be done during typing (= this looks like real dependent types). Maybe we can add some dedicated syntax, e.g. `set(at_typing_type=true, "audio.samplerate", 48000)`, but it requires changing the typing algorithm (which I don't like) and it's not going to be used much I guess...
