### ISSUE TITLE
Warnings don't allow running the program

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#994]
The following program
```
x = 5
output.dummy(sine())
```
results in
```
Line 3, char 0:
Warning 4: Unused variable x
No output defined, nothing to do.
```
In my opinion (and of some users on slack), the program should be run after issuing the warning (unless the flag `--strict` is passed). This was changed in 1.4.0 (presumably in https://github.com/savonet/liquidsoap/pull/790) and I don't think it is deliberate...

**Comment by smimram** [comment]
To be more precise, [here is the culprit](https://github.com/savonet/liquidsoap/pull/790/files#diff-84ccbca8728deab9d31a31fe3cbdc986R303).

**Comment by mcfiredrill** [comment]
Failing on warnings isn't such a big deal to me, but the message `No output defined, nothing to do.` was pretty confusing however as I had multiple outputs defined. :)

**Comment by toots** [comment]
I'm down to change this. We could do it in `1.4.3` as this shouldn't make any existing script fail.

**Comment by toots** [comment]
Ok, this bug is more annoying that I thought. The problem is that the refactorization of `Lang_errors` was done with the wrong workflow in mind. The idea was to raise and then let `Lang_errors` catch and ignore warnings. However, this mechanism stops the script's parsing, leading to confusing errors like this one and, I believe, this one too: https://github.com/savonet/liquidsoap/issues/1249. I'll see what I can do.
